.TH "ConfigData" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <setup\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigData\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBtype\fP = \fBGEIGIE_TYPE_B\fP"
.br
.ti -1c
.RI "uint8_t \fBmode\fP = \fBGEIGIE_MODE_USVH\fP"
.br
.ti -1c
.RI "char \fBuser_name\fP [\fBSETUP_USERNAME_MAXLEN\fP+1] = {0}"
.br
.ti -1c
.RI "uint32_t \fBdevice_id\fP = \fBSETUP_DEFAULT_DEVICE_ID\fP"
.br
.ti -1c
.RI "uint8_t \fBcpm_window\fP = \fBSETUP_DEFAULT_CPM_WINDOW\fP"
.br
.ti -1c
.RI "float \fBcpm2ush_divider\fP = \fBSETUP_DEFAULT_USH_DIVIDER\fP"
.br
.ti -1c
.RI "float \fBcpm2bqm2_factor\fP = \fBSETUP_DEFAULT_BQM2_FACTOR\fP"
.br
.ti -1c
.RI "uint32_t \fBalarm_level\fP = \fBSETUP_DEFAULT_ALARM_LEVEL\fP"
.br
.ti -1c
.RI "uint8_t \fBtimezone\fP = \fBSETUP_DEFAULT_TIMEZONE\fP"
.br
.ti -1c
.RI "char \fBcountry_code\fP [sizeof(\fBSETUP_DEFAULT_COUNTRY_CODE\fP)]"
.br
.ti -1c
.RI "uint8_t \fBsensor_type\fP = \fBSENSOR_TYPE_LND7317\fP"
.br
.ti -1c
.RI "uint8_t \fBsensor_shield\fP = \fBSENSOR_SHIELD_NONE\fP"
.br
.ti -1c
.RI "uint32_t \fBsensor_height\fP = \fBSETUP_DEFAULT_SENSOR_HEIGHT\fP"
.br
.ti -1c
.RI "uint8_t \fBsensor_mode\fP = \fBSENSOR_MODE_AIR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file setup\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConfigData::ConfigData ()\fC [inline]\fP"

.PP
Definition at line 71 of file setup\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void ConfigData::print () const\fC [inline]\fP"

.PP
Definition at line 87 of file setup\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t ConfigData::alarm_level = \fBSETUP_DEFAULT_ALARM_LEVEL\fP"

.PP
Definition at line 79 of file setup\&.hpp\&.
.SS "char ConfigData::country_code[sizeof(\fBSETUP_DEFAULT_COUNTRY_CODE\fP)]"

.PP
Definition at line 81 of file setup\&.hpp\&.
.SS "float ConfigData::cpm2bqm2_factor = \fBSETUP_DEFAULT_BQM2_FACTOR\fP"

.PP
Definition at line 78 of file setup\&.hpp\&.
.SS "float ConfigData::cpm2ush_divider = \fBSETUP_DEFAULT_USH_DIVIDER\fP"

.PP
Definition at line 77 of file setup\&.hpp\&.
.SS "uint8_t ConfigData::cpm_window = \fBSETUP_DEFAULT_CPM_WINDOW\fP"

.PP
Definition at line 76 of file setup\&.hpp\&.
.SS "uint32_t ConfigData::device_id = \fBSETUP_DEFAULT_DEVICE_ID\fP"

.PP
Definition at line 75 of file setup\&.hpp\&.
.SS "uint8_t ConfigData::mode = \fBGEIGIE_MODE_USVH\fP"

.PP
Definition at line 73 of file setup\&.hpp\&.
.SS "uint32_t ConfigData::sensor_height = \fBSETUP_DEFAULT_SENSOR_HEIGHT\fP"

.PP
Definition at line 84 of file setup\&.hpp\&.
.SS "uint8_t ConfigData::sensor_mode = \fBSENSOR_MODE_AIR\fP"

.PP
Definition at line 85 of file setup\&.hpp\&.
.SS "uint8_t ConfigData::sensor_shield = \fBSENSOR_SHIELD_NONE\fP"

.PP
Definition at line 83 of file setup\&.hpp\&.
.SS "uint8_t ConfigData::sensor_type = \fBSENSOR_TYPE_LND7317\fP"

.PP
Definition at line 82 of file setup\&.hpp\&.
.SS "uint8_t ConfigData::timezone = \fBSETUP_DEFAULT_TIMEZONE\fP"

.PP
Definition at line 80 of file setup\&.hpp\&.
.SS "uint8_t ConfigData::type = \fBGEIGIE_TYPE_B\fP"

.PP
Definition at line 72 of file setup\&.hpp\&.
.SS "char ConfigData::user_name[\fBSETUP_USERNAME_MAXLEN\fP+1] = {0}"

.PP
Definition at line 74 of file setup\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
