.TH "include/config.hpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/config.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <cstdlib>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const uint16_t \fBMAJOR\fP = 0"
.br
.ti -1c
.RI "const uint16_t \fBMINOR\fP = 1"
.br
.ti -1c
.RI "const uint16_t \fBPATCH\fP = 0"
.br
.ti -1c
.RI "const char \fBdevice_nickname\fP [] = 'zen'"
.br
.ti -1c
.RI "const char \fBDEVICE_HEADER\fP [] = 'BNRDD'"
.br
.ti -1c
.RI "const size_t \fBLOG_BUFFER_SIZE\fP = 100"
.br
.ti -1c
.RI "const size_t \fBGEIGER_AVERAGING_PERIOD_S\fP = 5"
.br
.ti -1c
.RI "const int \fBGEIGER_PULSE_GPIO\fP = 2"
.br
.ti -1c
.RI "const size_t \fBGEIGER_AVERAGING_N_BINS\fP = 12"
.br
.ti -1c
.RI "const float \fBGEIGER_SENSOR1_CPM_FACTOR\fP = 340\&.0"
.br
.ti -1c
.RI "const int \fBGPS_SERIAL_NUM\fP = 2"
.br
.ti -1c
.RI "const uint32_t \fBGPS_BAUD_RATE\fP = 9600"
.br
.ti -1c
.RI "const uint16_t \fBGPS_INVALID_YEAR\fP = 2000"
.br
.ti -1c
.RI "const uint32_t \fBLCD_REFRESH_RATE\fP = 1000"
.br
.ti -1c
.RI "const uint8_t \fBSD_CS_PIN\fP = 4"
.br
.ti -1c
.RI "const char \fBQR_CODE_URL_BASE\fP [] = 'http://tt\&.safecast\&.org/id/geigiecast:'"
.br
.ti -1c
.RI "const size_t \fBQR_CODE_DEV_ID_NDIGITS\fP = 4"
.br
.ti -1c
.RI "const char \fBLOG_HEADER_LINE1\fP [] = '# NEW LOG'"
.br
.ti -1c
.RI "const char \fBLOG_HEADER_LINE2\fP [] = '# format='"
.br
.ti -1c
.RI "const char \fBLOG_HEADER_LINE3\fP [] = '# deadtime=off'"
.br
.ti -1c
.RI "const char \fBSETUP_FILENAME\fP [] = '/SAFECAST\&.txt'"
.br
.ti -1c
.RI "const size_t \fBSETUP_FILE_PARSE_BUFFER_SIZE\fP = 102"
.br
.ti -1c
.RI "const uint32_t \fBSETUP_DEFAULT_DEVICE_ID\fP = 0"
.br
.ti -1c
.RI "const size_t \fBSETUP_USERNAME_MAXLEN\fP = 15"
.br
.ti -1c
.RI "const float \fBSETUP_DEFAULT_USH_DIVIDER\fP = 334\&.0"
.br
.ti -1c
.RI "const float \fBSETUP_DEFAULT_BQM2_FACTOR\fP = 37\&.0"
.br
.ti -1c
.RI "const uint32_t \fBSETUP_DEFAULT_SENSOR_HEIGHT\fP = 100"
.br
.ti -1c
.RI "const uint8_t \fBSETUP_DEFAULT_CPM_WINDOW\fP = 60"
.br
.ti -1c
.RI "const uint32_t \fBSETUP_DEFAULT_ALARM_LEVEL\fP = 100"
.br
.ti -1c
.RI "const char \fBSETUP_DEFAULT_COUNTRY_CODE\fP [4] = 'JPN'"
.br
.ti -1c
.RI "const uint8_t \fBSETUP_DEFAULT_TIMEZONE\fP = 9"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char DEVICE_HEADER[] = 'BNRDD'"

.PP
Definition at line 23 of file config\&.hpp\&.
.SS "const char device_nickname[] = 'zen'"

.PP
Definition at line 18 of file config\&.hpp\&.
.SS "const size_t GEIGER_AVERAGING_N_BINS = 12"

.PP
Definition at line 29 of file config\&.hpp\&.
.SS "const size_t GEIGER_AVERAGING_PERIOD_S = 5"

.PP
Definition at line 27 of file config\&.hpp\&.
.SS "const int GEIGER_PULSE_GPIO = 2"

.PP
Definition at line 28 of file config\&.hpp\&.
.SS "const float GEIGER_SENSOR1_CPM_FACTOR = 340\&.0"

.PP
Definition at line 30 of file config\&.hpp\&.
.SS "const uint32_t GPS_BAUD_RATE = 9600"

.PP
Definition at line 33 of file config\&.hpp\&.
.SS "const uint16_t GPS_INVALID_YEAR = 2000"

.PP
Definition at line 34 of file config\&.hpp\&.
.SS "const int GPS_SERIAL_NUM = 2"

.PP
Definition at line 32 of file config\&.hpp\&.
.SS "const uint32_t LCD_REFRESH_RATE = 1000"

.PP
Definition at line 36 of file config\&.hpp\&.
.SS "const size_t LOG_BUFFER_SIZE = 100"

.PP
Definition at line 25 of file config\&.hpp\&.
.SS "const char LOG_HEADER_LINE1[] = '# NEW LOG'"

.PP
Definition at line 43 of file config\&.hpp\&.
.SS "const char LOG_HEADER_LINE2[] = '# format='"

.PP
Definition at line 44 of file config\&.hpp\&.
.SS "const char LOG_HEADER_LINE3[] = '# deadtime=off'"

.PP
Definition at line 45 of file config\&.hpp\&.
.SS "const uint16_t MAJOR = 0"

.PP
Definition at line 15 of file config\&.hpp\&.
.SS "const uint16_t MINOR = 1"

.PP
Definition at line 16 of file config\&.hpp\&.
.SS "const uint16_t PATCH = 0"

.PP
Definition at line 17 of file config\&.hpp\&.
.SS "const size_t QR_CODE_DEV_ID_NDIGITS = 4"

.PP
Definition at line 41 of file config\&.hpp\&.
.SS "const char QR_CODE_URL_BASE[] = 'http://tt\&.safecast\&.org/id/geigiecast:'"

.PP
Definition at line 40 of file config\&.hpp\&.
.SS "const uint8_t SD_CS_PIN = 4"

.PP
Definition at line 38 of file config\&.hpp\&.
.SS "const uint32_t SETUP_DEFAULT_ALARM_LEVEL = 100"

.PP
Definition at line 55 of file config\&.hpp\&.
.SS "const float SETUP_DEFAULT_BQM2_FACTOR = 37\&.0"

.PP
Definition at line 52 of file config\&.hpp\&.
.SS "const char SETUP_DEFAULT_COUNTRY_CODE[4] = 'JPN'"

.PP
Definition at line 56 of file config\&.hpp\&.
.SS "const uint8_t SETUP_DEFAULT_CPM_WINDOW = 60"

.PP
Definition at line 54 of file config\&.hpp\&.
.SS "const uint32_t SETUP_DEFAULT_DEVICE_ID = 0"

.PP
Definition at line 49 of file config\&.hpp\&.
.SS "const uint32_t SETUP_DEFAULT_SENSOR_HEIGHT = 100"

.PP
Definition at line 53 of file config\&.hpp\&.
.SS "const uint8_t SETUP_DEFAULT_TIMEZONE = 9"

.PP
Definition at line 57 of file config\&.hpp\&.
.SS "const float SETUP_DEFAULT_USH_DIVIDER = 334\&.0"

.PP
Definition at line 51 of file config\&.hpp\&.
.SS "const size_t SETUP_FILE_PARSE_BUFFER_SIZE = 102"

.PP
Definition at line 48 of file config\&.hpp\&.
.SS "const char SETUP_FILENAME[] = '/SAFECAST\&.txt'"

.PP
Definition at line 47 of file config\&.hpp\&.
.SS "const size_t SETUP_USERNAME_MAXLEN = 15"

.PP
Definition at line 50 of file config\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
