.TH "src/display.cpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/display.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <M5Stack\&.h>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <display\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprintFloat\fP (float val, bool valid, int len, int prec)"
.br
.ti -1c
.RI "void \fBprintFloatFont\fP (float val, bool valid, int len, int prec, int y, int x, int font)"
.br
.ti -1c
.RI "void \fBprintInt\fP (unsigned long val, bool valid, int len)"
.br
.ti -1c
.RI "void \fBprintIntFont\fP (unsigned long val, bool valid, int len, int y, int x, int font)"
.br
.ti -1c
.RI "void \fBprintDate\fP (\fBTinyGPSDate\fP &d)"
.br
.ti -1c
.RI "void \fBprintTime\fP (\fBTinyGPSTime\fP &t)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void printDate (\fBTinyGPSDate\fP & d)"

.PP
Definition at line 230 of file display\&.cpp\&.
.SS "void printFloat (float val, bool valid, int len, int prec)"

.PP
Definition at line 171 of file display\&.cpp\&.
.SS "void printFloatFont (float val, bool valid, int len, int prec, int y, int x, int font)"

.PP
Definition at line 185 of file display\&.cpp\&.
.SS "void printInt (unsigned long val, bool valid, int len)"

.PP
Definition at line 207 of file display\&.cpp\&.
.SS "void printIntFont (unsigned long val, bool valid, int len, int y, int x, int font)"

.PP
Definition at line 218 of file display\&.cpp\&.
.SS "void printTime (\fBTinyGPSTime\fP & t)"

.PP
Definition at line 243 of file display\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
