.TH "DisplayData" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DisplayData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <display\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBdevice_id\fP"
.br
.ti -1c
.RI "bool \fBgeiger_fresh\fP = true"
.br
.ti -1c
.RI "bool \fBgeiger_valid\fP = false"
.br
.ti -1c
.RI "uint32_t \fBgeiger_cpm\fP = 0"
.br
.ti -1c
.RI "float \fBgeiger_uSv\fP = 0\&.0"
.br
.ti -1c
.RI "bool \fBgps_fresh\fP = true"
.br
.ti -1c
.RI "\fBTinyGPSInteger\fP \fBgps_satellites\fP"
.br
.ti -1c
.RI "\fBTinyGPSAltitude\fP \fBgps_altitude\fP"
.br
.ti -1c
.RI "\fBTinyGPSSpeed\fP \fBgps_speed\fP"
.br
.ti -1c
.RI "\fBTinyGPSCourse\fP \fBgps_course\fP"
.br
.ti -1c
.RI "\fBTinyGPSLocation\fP \fBgps_location\fP"
.br
.ti -1c
.RI "\fBTinyGPSTime\fP \fBgps_time\fP"
.br
.ti -1c
.RI "\fBTinyGPSDate\fP \fBgps_date\fP"
.br
.ti -1c
.RI "int8_t \fBbattery_level\fP = \-1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file display\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int8_t DisplayData::battery_level = \-1"

.PP
Definition at line 50 of file display\&.hpp\&.
.SS "uint32_t DisplayData::device_id"

.PP
Definition at line 31 of file display\&.hpp\&.
.SS "uint32_t DisplayData::geiger_cpm = 0"

.PP
Definition at line 36 of file display\&.hpp\&.
.SS "bool DisplayData::geiger_fresh = true"

.PP
Definition at line 34 of file display\&.hpp\&.
.SS "float DisplayData::geiger_uSv = 0\&.0"

.PP
Definition at line 37 of file display\&.hpp\&.
.SS "bool DisplayData::geiger_valid = false"

.PP
Definition at line 35 of file display\&.hpp\&.
.SS "\fBTinyGPSAltitude\fP DisplayData::gps_altitude"

.PP
Definition at line 42 of file display\&.hpp\&.
.SS "\fBTinyGPSCourse\fP DisplayData::gps_course"

.PP
Definition at line 44 of file display\&.hpp\&.
.SS "\fBTinyGPSDate\fP DisplayData::gps_date"

.PP
Definition at line 47 of file display\&.hpp\&.
.SS "bool DisplayData::gps_fresh = true"

.PP
Definition at line 40 of file display\&.hpp\&.
.SS "\fBTinyGPSLocation\fP DisplayData::gps_location"

.PP
Definition at line 45 of file display\&.hpp\&.
.SS "\fBTinyGPSInteger\fP DisplayData::gps_satellites"

.PP
Definition at line 41 of file display\&.hpp\&.
.SS "\fBTinyGPSSpeed\fP DisplayData::gps_speed"

.PP
Definition at line 43 of file display\&.hpp\&.
.SS "\fBTinyGPSTime\fP DisplayData::gps_time"

.PP
Definition at line 46 of file display\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
