.TH "DoseData" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DoseData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <setup\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBtotal_count\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBtotal_time\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file setup\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t DoseData::total_count = 0"

.PP
Definition at line 66 of file setup\&.hpp\&.
.SS "uint32_t DoseData::total_time = 0"

.PP
Definition at line 67 of file setup\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
