.TH "include/fsm_state_base.hpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/fsm_state_base.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <fsm_context\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBState\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEvent\fP { \fBEvent::DEVICE_STARTED\fP, \fBEvent::SETUP_FINISHED\fP, \fBEvent::GPS_DATE_BECAME_CORRECT\fP, \fBEvent::LOG_FILE_CREATED\fP, \fBEvent::GPS_GEIGER_COUNT_READY\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBEvent\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDEVICE_STARTED \fP\fP
.TP
\fB\fISETUP_FINISHED \fP\fP
.TP
\fB\fIGPS_DATE_BECAME_CORRECT \fP\fP
.TP
\fB\fILOG_FILE_CREATED \fP\fP
.TP
\fB\fIGPS_GEIGER_COUNT_READY \fP\fP
.PP
Definition at line 9 of file fsm_state_base\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
