.TH "include/hardwarecounter.hpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/hardwarecounter.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <limits>\fP
.br
\fC#include <M5Stack\&.h>\fP
.br
\fC#include <Ticker\&.h>\fP
.br
\fC#include <driver/pcnt\&.h>\fP
.br
\fC#include <config\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHardwareCounter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
