.TH "src/logger.cpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/logger.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <M5Stack\&.h>\fP
.br
\fC#include <logger\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBchecksum\fP (char *s, int N)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char checksum (char * s, int N)"

.PP
Definition at line 6 of file logger\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
