.TH "src/main.cpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <M5Stack\&.h>\fP
.br
\fC#include <fsm_context\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.ti -1c
.RI "void \fBloop\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBContext\fP \fBcontext\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void loop ()"

.PP
Definition at line 13 of file main\&.cpp\&.
.SS "void setup ()"

.PP
Definition at line 9 of file main\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBContext\fP context"

.PP
Definition at line 7 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
