.TH "md__r_e_a_d_m_e" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- bGeigie-Zen firmware (ESP32) 

.SH "Quick Start"
.PP
Pre-requisites: python3
.PP
.IP "1." 4
Install \fCPlatform IO CLI\fP 
.PP
.nf
 python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

.fi
.PP
 I haven't tried this step myself, but if it fails, try to follow the instructions on platform\&.io's website\&. Rob is using platform\&.io within VS Code\&. The link for that is \fChere\fP
.IP "3." 4
Clone the repository 
.PP
.nf
 git clone git@github.com:Safecast/bGeigie-Raku.git

.fi
.PP

.IP "4." 4
Change branch to Robin dev 
.PP
.nf
 cd bGeigie-Raku
 git checkout robin/M5Stack_bGeigieRaku_V2.0

.fi
.PP

.IP "5." 4
Change directory 
.PP
.nf
 cd bgeigie_firmware_pio

.fi
.PP

.IP "6." 4
Connect the device using USB, compile, and upload 
.PP
.nf
 pio run -t upload

.fi
.PP
 
.PP

