.TH "include/setup.hpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/setup.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstring>\fP
.br
\fC#include <M5Stack\&.h>\fP
.br
\fC#include <config\&.hpp>\fP
.br
\fC#include <Preferences\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDoseData\fP"
.br
.ti -1c
.RI "struct \fBConfigData\fP"
.br
.ti -1c
.RI "class \fBSetup\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGeigieType\fP { \fBGEIGIE_TYPE_B\fP = 0, \fBGEIGIE_TYPE_X\fP }"
.br
.ti -1c
.RI "enum \fBGeigieMode\fP { \fBGEIGIE_MODE_USVH\fP = 0, \fBGEIGIE_MODE_BQM2\fP }"
.br
.ti -1c
.RI "enum \fBSensorType\fP { \fBSENSOR_TYPE_LND7317\fP = 0, \fBSENSOR_TYPE_LND712\fP }"
.br
.ti -1c
.RI "enum \fBSensorShield\fP { \fBSENSOR_SHIELD_NONE\fP = 0, \fBSENSOR_SHIELD_ALPHA\fP, \fBSENSOR_SHIELD_ALPHABETA\fP }"
.br
.ti -1c
.RI "enum \fBSensorMode\fP { \fBSENSOR_MODE_AIR\fP = 0, \fBSENSOR_MODE_SURFACE\fP = 1, \fBSENSOR_MODE_PLANE\fP = 2 }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBSETUP_NAMESPACE\fP [] = 'bgzen\-data'"
.br
.ti -1c
.RI "const char \fBSETUP_KEY_CONFIG\fP [] = 'config'"
.br
.ti -1c
.RI "const char \fBSETUP_KEY_DOSE\fP [] = 'dose'"
.br
.ti -1c
.RI "const uint32_t \fBBNRDD_EEPROM_DOSE_WRITETIME\fP = 3600"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBGeigieMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIGEIGIE_MODE_USVH \fP\fP
.TP
\fB\fIGEIGIE_MODE_BQM2 \fP\fP
.PP
Definition at line 46 of file setup\&.hpp\&.
.SS "enum \fBGeigieType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIGEIGIE_TYPE_B \fP\fP
.TP
\fB\fIGEIGIE_TYPE_X \fP\fP
.PP
Definition at line 44 of file setup\&.hpp\&.
.SS "enum \fBSensorMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISENSOR_MODE_AIR \fP\fP
.TP
\fB\fISENSOR_MODE_SURFACE \fP\fP
.TP
\fB\fISENSOR_MODE_PLANE \fP\fP
.PP
Definition at line 59 of file setup\&.hpp\&.
.SS "enum \fBSensorShield\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISENSOR_SHIELD_NONE \fP\fP
.TP
\fB\fISENSOR_SHIELD_ALPHA \fP\fP
.TP
\fB\fISENSOR_SHIELD_ALPHABETA \fP\fP
.PP
Definition at line 53 of file setup\&.hpp\&.
.SS "enum \fBSensorType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISENSOR_TYPE_LND7317 \fP\fP
.TP
\fB\fISENSOR_TYPE_LND712 \fP\fP
.PP
Definition at line 48 of file setup\&.hpp\&.
.SH "Variable Documentation"
.PP 
.SS "const uint32_t BNRDD_EEPROM_DOSE_WRITETIME = 3600"

.PP
Definition at line 42 of file setup\&.hpp\&.
.SS "const char SETUP_KEY_CONFIG[] = 'config'"

.PP
Definition at line 37 of file setup\&.hpp\&.
.SS "const char SETUP_KEY_DOSE[] = 'dose'"

.PP
Definition at line 38 of file setup\&.hpp\&.
.SS "const char SETUP_NAMESPACE[] = 'bgzen\-data'"

.PP
Definition at line 36 of file setup\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
