.TH "StateStartup" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StateStartup
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fsm_state_concrete\&.hpp>\fP
.PP
Inherits \fBState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBon_enter\fP (\fBEvent\fP e)"
.br
.ti -1c
.RI "void \fBprocess\fP ()"
.br
.ti -1c
.RI "void \fBon_exit\fP (\fBEvent\fP e)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBStateStartup\fP * \fBinstance\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBStateStartup\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file fsm_state_concrete\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StateStartup::StateStartup ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 11 of file fsm_state_concrete\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBStateStartup\fP * StateStartup::instance ()\fC [static]\fP"

.PP
Definition at line 4 of file fsm_state_concrete\&.cpp\&.
.SS "void StateStartup::on_enter (\fBEvent\fP e)\fC [virtual]\fP"

.PP
Implements \fBState\fP\&.
.PP
Definition at line 10 of file fsm_state_concrete\&.cpp\&.
.SS "void StateStartup::on_exit (\fBEvent\fP e)\fC [virtual]\fP"

.PP
Implements \fBState\fP\&.
.PP
Definition at line 15 of file fsm_state_concrete\&.cpp\&.
.SS "void StateStartup::process ()\fC [virtual]\fP"

.PP
Implements \fBState\fP\&.
.PP
Definition at line 14 of file fsm_state_concrete\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
