.TH "TinyGPSHDOP" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyGPSHDOP
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TinyGPS++\&.h>\fP
.PP
Inherits \fBTinyGPSDecimal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBhdop\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 193 of file TinyGPS++\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double TinyGPSHDOP::hdop ()\fC [inline]\fP"

.PP
Definition at line 195 of file TinyGPS++\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
