.TH "TinyGPSDecimal" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyGPSDecimal
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TinyGPS++\&.h>\fP
.PP
Inherited by \fBTinyGPSAltitude\fP, \fBTinyGPSCourse\fP, \fBTinyGPSHDOP\fP, and \fBTinyGPSSpeed\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.ti -1c
.RI "bool \fBisUpdated\fP () const"
.br
.ti -1c
.RI "uint32_t \fBage\fP () const"
.br
.ti -1c
.RI "int32_t \fBvalue\fP ()"
.br
.ti -1c
.RI "\fBTinyGPSDecimal\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTinyGPSPlus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 132 of file TinyGPS++\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TinyGPSDecimal::TinyGPSDecimal ()\fC [inline]\fP"

.PP
Definition at line 141 of file TinyGPS++\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "uint32_t TinyGPSDecimal::age () const\fC [inline]\fP"

.PP
Definition at line 138 of file TinyGPS++\&.h\&.
.SS "bool TinyGPSDecimal::isUpdated () const\fC [inline]\fP"

.PP
Definition at line 137 of file TinyGPS++\&.h\&.
.SS "bool TinyGPSDecimal::isValid () const\fC [inline]\fP"

.PP
Definition at line 136 of file TinyGPS++\&.h\&.
.SS "int32_t TinyGPSDecimal::value ()\fC [inline]\fP"

.PP
Definition at line 139 of file TinyGPS++\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBTinyGPSPlus\fP\fC [friend]\fP"

.PP
Definition at line 134 of file TinyGPS++\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
