.TH "TinyGPSSpeed" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyGPSSpeed
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TinyGPS++\&.h>\fP
.PP
Inherits \fBTinyGPSDecimal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBknots\fP ()"
.br
.ti -1c
.RI "double \fBmph\fP ()"
.br
.ti -1c
.RI "double \fBmps\fP ()"
.br
.ti -1c
.RI "double \fBkmph\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 172 of file TinyGPS++\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double TinyGPSSpeed::kmph ()\fC [inline]\fP"

.PP
Definition at line 177 of file TinyGPS++\&.h\&.
.SS "double TinyGPSSpeed::knots ()\fC [inline]\fP"

.PP
Definition at line 174 of file TinyGPS++\&.h\&.
.SS "double TinyGPSSpeed::mph ()\fC [inline]\fP"

.PP
Definition at line 175 of file TinyGPS++\&.h\&.
.SS "double TinyGPSSpeed::mps ()\fC [inline]\fP"

.PP
Definition at line 176 of file TinyGPS++\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
