.TH "TinyGPSDate" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyGPSDate
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TinyGPS++\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.ti -1c
.RI "bool \fBisUpdated\fP () const"
.br
.ti -1c
.RI "uint32_t \fBage\fP () const"
.br
.ti -1c
.RI "uint32_t \fBvalue\fP ()"
.br
.ti -1c
.RI "uint16_t \fByear\fP ()"
.br
.ti -1c
.RI "uint8_t \fBmonth\fP ()"
.br
.ti -1c
.RI "uint8_t \fBday\fP ()"
.br
.ti -1c
.RI "\fBTinyGPSDate\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTinyGPSPlus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file TinyGPS++\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TinyGPSDate::TinyGPSDate ()\fC [inline]\fP"

.PP
Definition at line 96 of file TinyGPS++\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "uint32_t TinyGPSDate::age () const\fC [inline]\fP"

.PP
Definition at line 89 of file TinyGPS++\&.h\&.
.SS "uint8_t TinyGPSDate::day ()"

.PP
Definition at line 412 of file TinyGPS++\&.cpp\&.
.SS "bool TinyGPSDate::isUpdated () const\fC [inline]\fP"

.PP
Definition at line 88 of file TinyGPS++\&.h\&.
.SS "bool TinyGPSDate::isValid () const\fC [inline]\fP"

.PP
Definition at line 87 of file TinyGPS++\&.h\&.
.SS "uint8_t TinyGPSDate::month ()"

.PP
Definition at line 406 of file TinyGPS++\&.cpp\&.
.SS "uint32_t TinyGPSDate::value ()\fC [inline]\fP"

.PP
Definition at line 91 of file TinyGPS++\&.h\&.
.SS "uint16_t TinyGPSDate::year ()"

.PP
Definition at line 399 of file TinyGPS++\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBTinyGPSPlus\fP\fC [friend]\fP"

.PP
Definition at line 85 of file TinyGPS++\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
