.TH "TinyGPSCustom" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyGPSCustom
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TinyGPS++\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTinyGPSCustom\fP ()"
.br
.ti -1c
.RI "\fBTinyGPSCustom\fP (\fBTinyGPSPlus\fP &gps, const char *sentenceName, int termNumber)"
.br
.ti -1c
.RI "void \fBbegin\fP (\fBTinyGPSPlus\fP &gps, const char *_sentenceName, int _termNumber)"
.br
.ti -1c
.RI "bool \fBisUpdated\fP () const"
.br
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.ti -1c
.RI "uint32_t \fBage\fP () const"
.br
.ti -1c
.RI "const char * \fBvalue\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTinyGPSPlus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 199 of file TinyGPS++\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TinyGPSCustom::TinyGPSCustom ()\fC [inline]\fP"

.PP
Definition at line 202 of file TinyGPS++\&.h\&.
.SS "TinyGPSCustom::TinyGPSCustom (\fBTinyGPSPlus\fP & gps, const char * sentenceName, int termNumber)"

.PP
Definition at line 466 of file TinyGPS++\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "uint32_t TinyGPSCustom::age () const\fC [inline]\fP"

.PP
Definition at line 208 of file TinyGPS++\&.h\&.
.SS "void TinyGPSCustom::begin (\fBTinyGPSPlus\fP & gps, const char * _sentenceName, int _termNumber)"

.PP
Definition at line 471 of file TinyGPS++\&.cpp\&.
.SS "bool TinyGPSCustom::isUpdated () const\fC [inline]\fP"

.PP
Definition at line 206 of file TinyGPS++\&.h\&.
.SS "bool TinyGPSCustom::isValid () const\fC [inline]\fP"

.PP
Definition at line 207 of file TinyGPS++\&.h\&.
.SS "const char* TinyGPSCustom::value ()\fC [inline]\fP"

.PP
Definition at line 209 of file TinyGPS++\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBTinyGPSPlus\fP\fC [friend]\fP"

.PP
Definition at line 221 of file TinyGPS++\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
