.TH "src/TinyGPS++.cpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/TinyGPS++.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'TinyGPS++\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_GPRMCterm\fP   'GPRMC'"
.br
.ti -1c
.RI "#define \fB_GPGGAterm\fP   'GPGGA'"
.br
.ti -1c
.RI "#define \fB_GNRMCterm\fP   'GNRMC'"
.br
.ti -1c
.RI "#define \fB_GNGGAterm\fP   'GNGGA'"
.br
.ti -1c
.RI "#define \fBCOMBINE\fP(sentence_type,  term_number)   (((unsigned)(sentence_type) << 5) | term_number)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _GNGGAterm   'GNGGA'"

.PP
Definition at line 33 of file TinyGPS++\&.cpp\&.
.SS "#define _GNRMCterm   'GNRMC'"

.PP
Definition at line 32 of file TinyGPS++\&.cpp\&.
.SS "#define _GPGGAterm   'GPGGA'"

.PP
Definition at line 31 of file TinyGPS++\&.cpp\&.
.SS "#define _GPRMCterm   'GPRMC'"

.PP
Definition at line 30 of file TinyGPS++\&.cpp\&.
.SS "#define COMBINE(sentence_type, term_number)   (((unsigned)(sentence_type) << 5) | term_number)"

.PP
Definition at line 155 of file TinyGPS++\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
