var annotated_dup =
[
    [ "BatteryMonitorIP5306", "class_battery_monitor_i_p5306.html", "class_battery_monitor_i_p5306" ],
    [ "BGeigieLogFormatter", "class_b_geigie_log_formatter.html", "class_b_geigie_log_formatter" ],
    [ "ConfigData", "struct_config_data.html", "struct_config_data" ],
    [ "Context", "class_context.html", "class_context" ],
    [ "Display", "class_display.html", "class_display" ],
    [ "DisplayData", "struct_display_data.html", "struct_display_data" ],
    [ "DoseData", "struct_dose_data.html", "struct_dose_data" ],
    [ "GeigerCounter", "class_geiger_counter.html", "class_geiger_counter" ],
    [ "GPSSensor", "class_g_p_s_sensor.html", "class_g_p_s_sensor" ],
    [ "HardwareCounter", "class_hardware_counter.html", "class_hardware_counter" ],
    [ "RawDegrees", "struct_raw_degrees.html", "struct_raw_degrees" ],
    [ "SDLogger", "class_s_d_logger.html", "class_s_d_logger" ],
    [ "SDWrapper", "class_s_d_wrapper.html", "class_s_d_wrapper" ],
    [ "Setup", "class_setup.html", "class_setup" ],
    [ "State", "class_state.html", "class_state" ],
    [ "StateLogging", "class_state_logging.html", "class_state_logging" ],
    [ "StateStartup", "class_state_startup.html", "class_state_startup" ],
    [ "StateWaitGPSTime", "class_state_wait_g_p_s_time.html", "class_state_wait_g_p_s_time" ],
    [ "TinyGPSAltitude", "struct_tiny_g_p_s_altitude.html", "struct_tiny_g_p_s_altitude" ],
    [ "TinyGPSCourse", "struct_tiny_g_p_s_course.html", "struct_tiny_g_p_s_course" ],
    [ "TinyGPSCustom", "class_tiny_g_p_s_custom.html", "class_tiny_g_p_s_custom" ],
    [ "TinyGPSDate", "struct_tiny_g_p_s_date.html", "struct_tiny_g_p_s_date" ],
    [ "TinyGPSDecimal", "struct_tiny_g_p_s_decimal.html", "struct_tiny_g_p_s_decimal" ],
    [ "TinyGPSHDOP", "struct_tiny_g_p_s_h_d_o_p.html", "struct_tiny_g_p_s_h_d_o_p" ],
    [ "TinyGPSInteger", "struct_tiny_g_p_s_integer.html", "struct_tiny_g_p_s_integer" ],
    [ "TinyGPSLocation", "struct_tiny_g_p_s_location.html", "struct_tiny_g_p_s_location" ],
    [ "TinyGPSPlus", "class_tiny_g_p_s_plus.html", "class_tiny_g_p_s_plus" ],
    [ "TinyGPSSpeed", "struct_tiny_g_p_s_speed.html", "struct_tiny_g_p_s_speed" ],
    [ "TinyGPSTime", "struct_tiny_g_p_s_time.html", "struct_tiny_g_p_s_time" ]
];