#ifndef BGEIGIEZEN_BLUETOOTH_SETTINGS_H_
#define BGEIGIEZEN_BLUETOOTH_SETTINGS_H_

#define BLE_DATA_ADDR_SIZE    6
#define BLE_DATA_ADDR         {0x88, 0x6B, 0x0F, 0x09, 0x7C, 0x9A}

#define BLE_PROFILE_NAME                            "bGeigie advanced module"

#define BLE_DEVICE_INFO_MANUFACTURER                "Safecast"
#define BLE_DEVICE_INFO_MODEL                       "bGeigieNano ESP32"
#define BLE_DEVICE_INFO_FIRMWARE_REVISION           "1.0.0"
#define BLE_DEVICE_INFO_HARDWARE_REVISION           "1.0.0 REV-A"

#define SERVICE_PROFILE_UUID                        "1800"
#define CHARACTERISTIC_PROFILE_NAME_UUID            "2a00"
#define CHARACTERISTIC_PROFILE_APPEARANCE_UUID      "2a01"

#define SERVICE_DEVICE_UUID                         "180A"
#define CHARACTERISTIC_DEVICE_MANUFACTURER_UUID     "2a29"
#define CHARACTERISTIC_DEVICE_MODEL_UUID            "2a24"
#define CHARACTERISTIC_DEVICE_FIRMWARE_UUID         "2a26"
#define CHARACTERISTIC_DEVICE_REVISION_UUID         "2a27"

#define SERVICE_DATA_UUID                           "EF080D8C-C3BE-41FF-BD3F-05A5F4795D7F"
#define CHARACTERISTIC_DATA_BDADDR_UUID             "38117F3C-28AB-4718-AB95-172B363F2AE0"
#define CHARACTERISTIC_DATA_BAUD_UUID               "2FBC0F31-726A-4014-B9FE-C8BE0652E982"
#define CHARACTERISTIC_DATA_RX_UUID                 "A1E8F5B1-696B-4E4C-87C6-69DFE0B0093B"
#define CHARACTERISTIC_DATA_TX_UUID                 "1494440E-9A58-4CC0-81E4-DDEA7F74F623"

#endif //BGEIGIEZEN_BLUETOOTH_SETTINGS_H_
