Raku_code.cpp
NX
TIME_INTERVAL
IS_READY
FF17
FF18
FF20
IP5306_REG_SYS_0
IP5306_REG_SYS_1
IP5306_REG_SYS_2
IP5306_REG_CHG_0
IP5306_REG_CHG_1
IP5306_REG_CHG_2
IP5306_REG_CHG_3
IP5306_REG_CHG_4
IP5306_REG_READ_0
IP5306_REG_READ_1
IP5306_REG_READ_2
IP5306_REG_READ_3
IP5306_REG_READ_4
IP5306_GetKeyOffEnabled
IP5306_SetKeyOffEnabled
IP5306_GetBoostOutputEnabled
IP5306_SetBoostOutputEnabled
IP5306_GetPowerOnLoadEnabled
IP5306_SetPowerOnLoadEnabled
IP5306_GetChargerEnabled
IP5306_SetChargerEnabled
IP5306_GetBoostEnabled
IP5306_SetBoostEnabled
IP5306_GetLowBatShutdownEnable
IP5306_SetLowBatShutdownEnable
IP5306_GetBoostAfterVin
IP5306_SetBoostAfterVin
IP5306_GetShortPressBoostSwitchEnable
IP5306_SetShortPressBoostSwitchEnable
IP5306_GetFlashlightClicks
IP5306_SetFlashlightClicks
IP5306_GetBoostOffClicks
IP5306_SetBoostOffClicks
IP5306_GetLightLoadShutdownTime
IP5306_SetLightLoadShutdownTime
IP5306_GetLongPressTime
IP5306_SetLongPressTime
IP5306_GetChargingFullStopVoltage
IP5306_SetChargingFullStopVoltage
IP5306_GetChargeUnderVoltageLoop
IP5306_SetChargeUnderVoltageLoop
IP5306_GetEndChargeCurrentDetection
IP5306_SetEndChargeCurrentDetection
IP5306_GetVoltagePressure
IP5306_SetVoltagePressure
IP5306_GetChargeCutoffVoltage
IP5306_SetChargeCutoffVoltage
IP5306_GetChargeCCLoop
IP5306_SetChargeCCLoop
IP5306_GetVinCurrent
IP5306_SetVinCurrent
IP5306_GetShortPressDetected
IP5306_ClearShortPressDetected
IP5306_GetLongPressDetected
IP5306_ClearLongPressDetected
IP5306_GetDoubleClickDetected
IP5306_ClearDoubleClickDetected
IP5306_GetPowerSource
IP5306_GetBatteryFull
IP5306_GetOutputLoad
IP5306_GetLevelLeds
IP5306_LEDS2PCT
int S1peak
Referenced by loop.
float conversionCoefficient
Referenced by loop, setup.
float sensor1_cpm_factor
Referenced by loop.
unsigned long previousMillis
unsigned long currentmillis
unsigned long total_time
unsigned long shift_reg[NX][NX]
Referenced by cpm_gen, loop.
unsigned long reg_index
Referenced by loop.
unsigned long total_count
Referenced by interruptCounterCount, loop.
unsigned long max_count
unsigned long uptime
unsigned long _start_time
Referenced by interruptCounterAvailable, interruptCounterReset.
unsigned long _delay
Referenced by interruptCounterAvailable.
unsigned long _count
unsigned long cpm
Referenced by loop.
unsigned long cpb
Referenced by loop.
unsigned long updateIntervalInMillis
unsigned long int counts_per_sample
Referenced by interruptCounterCount, interruptCounterReset, onPulse.
TinyGPSPlus gps
Referenced by TinyGPSCustom::begin, Display::feed, BGeigieLogFormatter::feed, SatelliteViewScreen::handle_input, GFXScreen::handle_report, loop, LocalStorage::produce_data, DebugModeScreen::render, DriveModeScreen::render, SatelliteViewScreen::render, SurveyModeScreen::render, TinyGPSCustom::TinyGPSCustom.
const uint32_t GPSBaud
unsigned long elapsedTime(unsigned long startTime)
HardwareSerial ss(2)
Referenced by GPSSensor::GPSSensor, setup.
unsigned long cpm_gen()
References clamp, NX, shift_reg.
Referenced by loop.
void onPulse()
References counts_per_sample.
Referenced by setup.
void interruptCounterReset()
References _start_time, clamp, counts_per_sample.
Referenced by loop.
int interruptCounterAvailable()
References _delay, _start_time, clamp.
unsigned long interruptCounterCount()
References counts_per_sample, total_count.
Referenced by loop.
int8_t getBatteryLevel()
References clamp.
Referenced by loop.
static void smartDelay(unsigned long ms)
static void printFloat(float val, bool valid, int len, int prec)
static void printFloatFont(float val, bool valid, int len, int prec, int y, int x, int font)
static void printInt(unsigned long val, bool valid, int len)
static void printIntFont(unsigned long val, bool valid, int len, int y, int x, int font)
static void printDate(TinyGPSDate &d)
static void printTime(TinyGPSTime &t)
int ip5306_get_reg(uint8_t reg)
References clamp.
Referenced by ip5306_get_bits, ip5306_set_bits.
int ip5306_set_reg(uint8_t reg, uint8_t value)
References clamp.
Referenced by ip5306_set_bits.
uint8_t ip5306_get_bits(uint8_t reg, uint8_t index, uint8_t bits)
References clamp, ip5306_get_reg.
void ip5306_set_bits(uint8_t reg, uint8_t index, uint8_t bits, uint8_t value)
References clamp, ip5306_get_reg, ip5306_set_reg.
void printIP5306Stats()
References clamp, IP5306_GetBatteryFull, IP5306_GetLevelLeds, IP5306_GetPowerSource, IP5306_LEDS2PCT.
Referenced by loop.
void printIP5306Settings()
References clamp, IP5306_GetBoostAfterVin, IP5306_GetBoostEnabled, IP5306_GetBoostOffClicks, IP5306_GetBoostOutputEnabled, IP5306_GetChargeCCLoop, IP5306_GetChargeCutoffVoltage, IP5306_GetChargerEnabled, IP5306_GetChargeUnderVoltageLoop, IP5306_GetChargingFullStopVoltage, IP5306_GetEndChargeCurrentDetection, IP5306_GetFlashlightClicks, IP5306_GetKeyOffEnabled, IP5306_GetLightLoadShutdownTime, IP5306_GetLongPressTime, IP5306_GetLowBatShutdownEnable, IP5306_GetPowerOnLoadEnabled, IP5306_GetShortPressBoostSwitchEnable, IP5306_GetVinCurrent, IP5306_GetVoltagePressure.
Referenced by setup.
void setup()
References clamp, conversionCoefficient, onPulse, printIP5306Settings, ss.
void loop()
References TinyGPSPlus::altitude, TinyGPSPlus::charsProcessed, clamp, conversionCoefficient, TinyGPSPlus::course, cpb, cpm, cpm_gen, TinyGPSPlus::date, TinyGPSCourse::deg, getBatteryLevel, gps, interruptCounterCount, interruptCounterReset, IS_READY, TinyGPSLocation::isValid, TinyGPSDecimal::isValid, TinyGPSInteger::isValid, TinyGPSSpeed::kmph, TinyGPSLocation::lat, TinyGPSLocation::lng, TinyGPSPlus::location, TinyGPSAltitude::meters, NX, printDate, printFloat, printFloatFont, printInt, printIntFont, printIP5306Stats, printTime, reg_index, S1peak, TinyGPSPlus::satellites, sensor1_cpm_factor, shift_reg, TinyGPSPlus::speed, TinyGPSPlus::time, total_count, TinyGPSInteger::value.