configuration_server.cpp
RETRY_TIMEOUT
T clamp(T2 val, T min, T max)
Referenced by actionAbout, ApiConnector::activate, BluetoothReporter::activate, SdLogger::activate, GeigerCounter::activate, GpsConnector::activate, NavsatCollector::activate, DateTimeProvider::activate, ShakeDetector::activate, LocalStorage::activate, CircularBuffer< T, max >::add, TinyGPSLocation::age, TinyGPSDate::age, TinyGPSTime::age, TinyGPSDecimal::age, TinyGPSInteger::age, TinyGPSCustom::age, GPSSensor::age_ms, WiFiConnection::ap_server_up, WiFiWrapper::ap_server_up, BaseScreen::BaseScreen, HardwareCounter::begin, SDWrapper::begin, SDInterface::begin, TinyGPSCustom::begin, TinyGPSPlus::cardinal, TinyGPS::cardinal, checksum, checksum, Display::clear, LocalStorage::clear, BaseScreen::clear_screen_content, ConfigData::ConfigData, GeigerCounter::configure, WiFiConnection::connect_wifi, WiFiWrapper::connect_wifi, core2Brightness, TinyGPS::course_to, TinyGPSPlus::courseTo, cpm_gen, dd_to_dm, ApiConnector::deactivate, BluetoothReporter::deactivate, SdLogger::deactivate, SDInterface::delete_log, WiFiConnection::disconnect_wifi, WiFiWrapper::disconnect_wifi, TinyGPS::distance_between, TinyGPSPlus::distanceBetween, BaseScreen::do_render, Display::draw_base, Display::draw_main, Display::draw_menu, Display::draw_navbar, Display::draw_navbar_label, Display::draw_qrcode, Display::draw_survey, BaseScreen::drawButton1, BaseScreen::drawButton2, BaseScreen::drawButton3, TinyGPS::encode, TinyGPSPlus::encode, SDInterface::end, State::enter, State::enter, BootScreen::enter_screen, ConfigModeScreen::enter_screen, SatelliteViewScreen::enter_screen, SdMessageScreen::enter_screen, State::exit, State::exit, TinyGPS::f_get_position, TinyGPS::f_speed_kmph, TinyGPS::f_speed_mph, TinyGPS::f_speed_mps, BGeigieLogFormatter::feed, Display::feed_battery_level, BGeigieLogFormatter::format, GeigerCounter::GeigerCounter, CircularBuffer< T, max >::get, HttpPages::get_config_connection_page, HttpPages::get_config_device_page, HttpPages::get_config_location_page, Measurement< T >::get_data, TinyGPS::get_datetime, BaseScreen::get_error_message, HttpPages::get_home_page, TinyGPS::get_position, BaseScreen::get_status_message, get_wgs84_coordinate, getBatteryLevel, MenuContext::goto_state, MenuContext::goto_state, GPSSensor::GPSSensor, ApiConnector::handle_async, BluetoothReporter::handle_async, BootScreen::handle_input, ConfigModeScreen::handle_input, DebugModeScreen::handle_input, DefaultEntryScreen::handle_input, DriveModeScreen::handle_input, FirstTimeStartupScreen::handle_input, FixedModeScreen::handle_input, MenuWindow::handle_input, SatelliteViewScreen::handle_input, SdMessageScreen::handle_input, SurveyModeScreen::handle_input, ZenInfoScreen::handle_input, BaseScreenWithMenu::handle_menu_input, ApiConnector::handle_produced_work, BluetoothReporter::handle_produced_work, SdLogger::handle_produced_work, GFXScreen::handle_report, SDInterface::has_safezen_content, haversine_km, SDInterface::i, GPSThread::init, GFXScreen::initialize, StateStartup::instance, StateWaitGPSTime::instance, StateLogging::instance, interruptCounterAvailable, interruptCounterReset, ip5306_get_bits, ip5306_get_reg, ip5306_set_bits, ip5306_set_reg, SDInterface::just_wrote, TinyGPSLocation::lat, TinyGPSLocation::lng, Setup::load_from_file, SDLogger::log, SDInterface::log_println, Context::loop, loop, MotionDetect::motionDetected, NavsatCollector::NavsatCollector, InitState::on_entry, ConfigState::on_entry, InactiveState::on_entry, StateWaitGPSTime::on_exit, InitState::on_exit, ConfigState::on_exit, InactiveState::on_exit, BaseScreenWithMenu::open_menu, TinyGPS::operator<<, TinyGPSPlus::operator<<, TinyGPSPlus::parseDecimal, TinyGPSPlus::parseDegrees, pcnt_intr_handler, GPSThread::prepare_data, ConfigData::print, printDate, printFloat, printFloatFont, BaseScreen::printFloatFont, printInt, printIntFont, BaseScreen::printIntFont, printIP5306Settings, printIP5306Stats, printTime, StateLogging::process, BatteryIndicator::produce_data, GeigerCounter::produce_data, GpsConnector::produce_data, NavsatCollector::produce_data, ShakeDetector::produce_data, ZenButton::produce_data, LocalStorage::produce_data, DateTimeProvider::produce_data, LogAggregator::produce_data, SDInterface::read_safezen_file_to_settings, ApiConnector::reading_to_json, SDInterface::ready, Subject::register_observer, SDInterface::rename_log, BootScreen::render, ConfigModeScreen::render, DebugModeScreen::render, DriveModeScreen::render, FirstTimeStartupScreen::render, FixedModeScreen::render, MenuWindow::render, SatelliteViewScreen::render, SdMessageScreen::render, SurveyModeScreen::render, ZenInfoScreen::render, BaseScreenWithMenu::render_menu, HardwareCounter::reset, LocalStorage::reset_defaults, LocalStorage::set_alert_threshold, LocalStorage::set_animated_screensaver, LocalStorage::set_ap_password, LocalStorage::set_api_key, LocalStorage::set_cpm_usvh, LocalStorage::set_device_id, Display::set_dimblank_delays, LocalStorage::set_dop_max, LocalStorage::set_enable_journal, LocalStorage::set_fixed_latitude, LocalStorage::set_fixed_longitude, LocalStorage::set_fixed_range, WiFiConnection::set_hostname, WiFiWrapper::set_hostname, LocalStorage::set_last_latitude, LocalStorage::set_last_longitude, LocalStorage::set_last_mode, LocalStorage::set_log_void, LocalStorage::set_manual_logging, LocalStorage::set_screen_dim_timeout, LocalStorage::set_screen_off_timeout, BaseScreen::set_status_message, LocalStorage::set_wifi_password, LocalStorage::set_wifi_ssid, MotionDetect::setAccelThreshold, MotionDetect::setGyroThreshold, Context::setup, setup, SDInterface::setup_log, Display::showBatteryLevel, Display::showDeviceId, DeviceUtils::shutdown, SDLogger::start, WiFiConnection::start_ap_server, WiFiWrapper::start_ap_server, Controller::start_default_workers, TinyGPS::stats, WiFiWrapper::status, WiFiConnection::stop_ap_server, WiFiWrapper::stop_ap_server, timer_intr_handler, TinyGPS::TinyGPS, TinyGPSCustom::TinyGPSCustom, Context::transition_to, Display::update, GeigerCounter::update, GPSSensor::update, MotionDetect::update, InitState::update, WiFiWrapper::update_active, WiFiWrapper::was_active, WiFiConnection::wifi_connected, WiFiWrapper::wifi_connected, SDInterface::write_safezen_file_from_settings.