main.cpp
TeenyUbloxConnect gnss
The bGeigieZen is the next generation, modern Open Source customizable Geiger Counter. The followup to the successful bGeigieNanoKit. Homepage: https://bgeigiezen.safecast.jp/ GitHub https://github.com/Safecast/bGeigieZen wiki: https://github.com/Safecast/bGeigieZen/wiki Slack channel: bgeigiezen Copyright (c) 2024, Safecast All rights reserved. Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. Neither the name of the <organization> nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. History Versions: Contact:
Referenced by loop.
LocalStorage settings
Referenced by HttpPages::get_config_connection_page, HttpPages::get_config_device_page, HttpPages::get_config_location_page, HttpPages::get_home_page, BootScreen::handle_input, DefaultEntryScreen::handle_input, SdLogger::handle_produced_work, SDInterface::read_safezen_file_to_settings, DriveModeScreen::render, FirstTimeStartupScreen::render, FixedModeScreen::render, SurveyModeScreen::render, setup, SDInterface::write_safezen_file_from_settings.
Controller controller(settings, gnss)(settings, gnss)
Referenced by ConfigModeScreen::enter_screen, DriveModeScreen::enter_screen, FirstTimeStartupScreen::enter_screen, FixedModeScreen::enter_screen, SatelliteViewScreen::enter_screen, SdMessageScreen::enter_screen, SurveyModeScreen::enter_screen, BootScreen::handle_input, ConfigModeScreen::handle_input, DriveModeScreen::handle_input, MenuWindow::handle_input, SatelliteViewScreen::handle_input, SdMessageScreen::handle_input, SurveyModeScreen::handle_input, BaseScreenWithMenu::handle_menu_input, ConfigModeScreen::leave_screen, DriveModeScreen::leave_screen, FixedModeScreen::leave_screen, SatelliteViewScreen::leave_screen, SurveyModeScreen::leave_screen, loop, setup.
GpsConnector gps(gnss, Serial2)(gnss, Serial2)
Referenced by loop, setup.
NavsatCollector navsat(gnss)(gnss)
Referenced by SatelliteViewScreen::handle_input, SatelliteViewScreen::render, setup.
GeigerCounter gm_sensor
Referenced by LogAggregator::produce_data, DebugModeScreen::render, DriveModeScreen::render, FixedModeScreen::render, SurveyModeScreen::render, setup.
BatteryIndicator battery_indicator
Referenced by setup.
DateTimeProvider rtc
Referenced by GFXScreen::handle_report, DebugModeScreen::render, setup.
ShakeDetector shake_detector
Referenced by setup.
LogAggregator log_aggregator(settings)(settings)
Referenced by ApiConnector::handle_produced_work, DebugModeScreen::render, DriveModeScreen::render, FixedModeScreen::render, setup.
ConfigWebServer config_server(settings)(settings)
Referenced by setup.
SdLogger journal_logger(settings, SdLogger::journal)(settings, SdLogger::journal)
Referenced by setup.
SdLogger drive_logger(settings, SdLogger::drive)(settings, SdLogger::drive)
Referenced by setup.
SdLogger survey_logger(settings, SdLogger::survey)(settings, SdLogger::survey)
Referenced by setup.
BluetoothReporter bt_connector(settings)(settings)
Referenced by setup.
ApiConnector api_connector(settings)(settings)
Referenced by FixedModeScreen::render, setup.
GFXScreen gfx_screen(settings, controller)(settings, controller)
Referenced by setup.
ZenButton zen_A(M5.BtnA)
Referenced by setup.
ZenButton zen_B(M5.BtnB)
Referenced by setup.
ZenButton zen_C(M5.BtnC)
Referenced by setup.
void setup()
References api_connector, battery_indicator, bt_connector, clamp, config_server, controller, drive_logger, gfx_screen, gm_sensor, gps, journal_logger, k_handler_api_reporter, k_handler_bluetooth_reporter, k_handler_drive_logger, k_handler_journal_logger, k_handler_survey_logger, k_worker_battery_indicator, k_worker_button_1, k_worker_button_2, k_worker_button_3, k_worker_config_server, k_worker_device_state, k_worker_gm_sensor, k_worker_gps_connector, k_worker_local_storage, k_worker_log_aggregator, k_worker_navsat_collector, k_worker_rtc_connector, k_worker_shake_detector, log_aggregator, navsat, rtc, settings, shake_detector, Controller::start_default_workers, survey_logger, zen_A, zen_B, zen_C.
void loop()
References clamp, controller, gnss, gps.