GeigerCounter
HardwareCounter GeigerCounter::pulse_counter
float GeigerCounter::_ush_factor
float GeigerCounter::_bqm2_factor
float GeigerCounter::_cpm2ush_divider
uint32_t GeigerCounter::_cpm_alarm_level
int GeigerCounter::_pos
std::array< uint32_t, GEIGER_AVERAGING_N_BINS > GeigerCounter::_shift_reg
bool GeigerCounter::_available
bool GeigerCounter::_valid
uint32_t GeigerCounter::_cpb
uint32_t GeigerCounter::_cpm_raw
uint32_t GeigerCounter::_cpm_comp
uint32_t GeigerCounter::_cpm_comp_peak
uint32_t GeigerCounter::_total
float GeigerCounter::_uSv
float GeigerCounter::_Bqm2
uint32_t GeigerCounter::_cpm_alert_level
GeigerCounter::GeigerCounter(uint32_t time_interval, int gpio, float cpm2ush_divider, float bqm2_factor, uint32_t cpm_alarm_level)
References clamp, configure.
GeigerCounter::GeigerCounter(uint32_t time_interval, int gpio)
void GeigerCounter::configure(float cpm2ush_divider, float bqm2_factor, uint32_t cpm_alarm_level)
References clamp.
Referenced by GeigerCounter, Context::setup.
void GeigerCounter::begin()
References HardwareCounter::begin.
Referenced by Context::setup.
uint32_t GeigerCounter::per_bin() const
Referenced by BGeigieLogFormatter::feed.
uint32_t GeigerCounter::total() const
Referenced by BGeigieLogFormatter::feed.
uint32_t GeigerCounter::peak_per_minute() const
uint32_t GeigerCounter::per_minute_raw() const
Referenced by BGeigieLogFormatter::feed.
uint32_t GeigerCounter::per_minute() const
Referenced by Display::feed.
float GeigerCounter::uSv() const
Referenced by Display::feed.
float GeigerCounter::uSv_single_bin() const
float GeigerCounter::Bqm2() const
Referenced by DebugModeScreen::render.
float GeigerCounter::Bqm2_single_bin() const
bool GeigerCounter::alarm() const
size_t GeigerCounter::n_bins() const
bool GeigerCounter::valid() const
Referenced by Display::feed, BGeigieLogFormatter::feed, DebugModeScreen::render, DriveModeScreen::render, FixedModeScreen::render, SurveyModeScreen::render.
bool GeigerCounter::available() const
Referenced by StateWaitGPSTime::process, StateLogging::process.
void GeigerCounter::consume()
Referenced by Context::on_geiger_counter_available.
void GeigerCounter::update()
References HardwareCounter::available, clamp, HardwareCounter::get_last_count.
Referenced by Context::loop.
GeigerCounter::GeigerCounter(uint32_t time_interval, int gpio, float cpm2ush_divider, float bqm2_factor, uint32_t cpm_alarm_level)
References clamp, configure.
GeigerCounter::GeigerCounter(uint32_t time_interval, int gpio)
void GeigerCounter::configure(float cpm2ush_divider, float bqm2_factor, uint32_t cpm_alarm_level)
References clamp.
void GeigerCounter::begin()
References HardwareCounter::begin.
uint32_t GeigerCounter::per_bin() const
uint32_t GeigerCounter::total() const
uint32_t GeigerCounter::peak_per_minute() const
uint32_t GeigerCounter::per_minute_raw() const
uint32_t GeigerCounter::per_minute() const
float GeigerCounter::uSv() const
float GeigerCounter::uSv_single_bin() const
float GeigerCounter::Bqm2() const
float GeigerCounter::Bqm2_single_bin() const
bool GeigerCounter::alarm() const
size_t GeigerCounter::n_bins() const
bool GeigerCounter::valid() const
bool GeigerCounter::available() const
void GeigerCounter::consume()
void GeigerCounter::update()
GeigerCounter::GeigerCounter()
virtual GeigerCounter::~GeigerCounter()=default
bool GeigerCounter::activate(bool retry) override
References HardwareCounter::available, HardwareCounter::begin, clamp, HardwareCounter::get_last_count.
int8_t GeigerCounter::produce_data() override
References HardwareCounter::available, clamp, GEIGER_AVERAGING_N_BINS, HardwareCounter::get_last_count.