WiFiConnection
char WiFiConnection::myWifiSSID[32][32]
char WiFiConnection::myIPaddr[16][16]
char WiFiConnection::configWifiSSID[32][32]
char WiFiConnection::configWifiPreSharedKey[32][32]
char WiFiConnection::configIPaddr[20][20]
bool WiFiConnection::connect_wifi(const char *ssid, const char *password=nullptr)
Connect to wifi endpoint ssid password true if connected
References clamp.
void WiFiConnection::disconnect_wifi()
disconnect from wifi endpoint
References clamp.
bool WiFiConnection::wifi_connected()
check if wifi is connected
References clamp.
Referenced by ConfigWebServer::activate.
bool WiFiConnection::start_ap_server(const char *host_ssid, const char *password)
Start access point server true if up
References ACCESS_POINT_IP, ACCESS_POINT_NMASK, clamp, set_hostname.
void WiFiConnection::stop_ap_server()
Stop access point server
References clamp.
bool WiFiConnection::ap_server_up()
check if wifi is connected
References clamp.
Referenced by ConfigWebServer::activate.
void WiFiConnection::set_hostname(const char *hostname)
Set wifi hostname
References clamp.
Referenced by ConfigWebServer::activate, start_ap_server.