BaseScreenWithMenu
int BaseScreenWithMenu::_current_page
Referenced by ConfigModeScreen::enter_screen, SatelliteViewScreen::enter_screen, ConfigModeScreen::handle_input, SatelliteViewScreen::handle_input, handle_menu_input, ConfigModeScreen::leave_screen, ConfigModeScreen::render.
int BaseScreenWithMenu::_menu_index
Referenced by ConfigModeScreen::enter_screen, handle_menu_input, render_menu.
bool BaseScreenWithMenu::_menu_open
bool BaseScreenWithMenu::menu_open() const
True if menu view is open
Referenced by ConfigModeScreen::handle_input, SatelliteViewScreen::handle_input, GFXScreen::handle_report, ConfigModeScreen::render, MenuWindow::render, SatelliteViewScreen::render.
BaseScreenWithMenu::BaseScreenWithMenu(const char *title, bool status_bar)
BaseScreen * BaseScreenWithMenu::handle_menu_input(Controller &controller, const worker_map_t &workers, const MenuItem items[], int menu_max)
Handle input for the menu view (when menu is open) controller workers items all menu items menu_max length of menu items
References _current_page, _menu_index, clamp, controller, BaseScreen::enter_screen, BaseScreen::force_next_render, k_worker_button_1, k_worker_button_2, k_worker_button_3, BaseScreen::leave_screen.
Referenced by ConfigModeScreen::handle_input, MenuWindow::handle_input, SatelliteViewScreen::handle_input.
void BaseScreenWithMenu::render_menu(const MenuItem items[], int menu_max, bool outline=true, int outline_button=0)
Render menu view items all menu items menu_max length of menu items outline if true it will draw an outline around the menu outline_button visually connect to button (only button 3 supported)
References _menu_index, clamp, BaseScreen::drawButton1, BaseScreen::drawButton2, BaseScreen::drawButton3, BaseScreen::e_button_active, BaseScreen::e_button_disabled, LCD_COLOR_BACKGROUND, LCD_COLOR_DEFAULT, LCD_COLOR_ERROR, LCD_COLOR_INACTIVE, LCD_COLOR_STALE_INCOMPLETE.
Referenced by ConfigModeScreen::render, MenuWindow::render, SatelliteViewScreen::render.
void BaseScreenWithMenu::open_menu(bool open)
Open or close the menu
References clamp.
Referenced by ConfigModeScreen::enter_screen, MenuWindow::enter_screen, SatelliteViewScreen::enter_screen, ConfigModeScreen::handle_input, SatelliteViewScreen::handle_input, MenuWindow::leave_screen.