BaseScreen
ButtonState
bool BaseScreen::required_gps
Referenced by DriveModeScreen::DriveModeScreen, FixedModeScreen::FixedModeScreen, get_error_message, has_required_gps, SatelliteViewScreen::SatelliteViewScreen, SurveyModeScreen::SurveyModeScreen.
bool BaseScreen::required_sd
Referenced by DriveModeScreen::DriveModeScreen, get_error_message, has_required_sd, SurveyModeScreen::SurveyModeScreen.
bool BaseScreen::required_tube
Referenced by DriveModeScreen::DriveModeScreen, FixedModeScreen::FixedModeScreen, get_error_message, has_required_tube, SurveyModeScreen::SurveyModeScreen.
bool BaseScreen::required_wifi
Referenced by FixedModeScreen::FixedModeScreen, get_error_message, has_required_wifi.
bool BaseScreen::required_ble
Referenced by has_required_ble.
char BaseScreen::_title[20][20]
bool BaseScreen::_status_bar
bool BaseScreen::_force_render
uint32_t BaseScreen::_status_message_time
const __FlashStringHelper* BaseScreen::_message
virtual BaseScreen * BaseScreen::handle_input(Controller &controller, const worker_map_t &workers)=0
Referenced by GFXScreen::handle_report.
void BaseScreen::enter_screen(Controller &controller)
Enter the screen, use controller to enable screen specific workers/handlers controller
Referenced by BaseScreenWithMenu::handle_menu_input, GFXScreen::handle_report, GFXScreen::initialize.
void BaseScreen::leave_screen(Controller &controller)
Leave the screen, use controller to disable screen specific workers/handlers controller
Referenced by BaseScreenWithMenu::handle_menu_input, GFXScreen::handle_report.
void BaseScreen::do_render(const worker_map_t &workers, const handler_map_t &handlers) final
Render the screen with latest data workers handlers
References clamp, render.
Referenced by GFXScreen::handle_report.
void BaseScreen::force_next_render() final
Render the screen with latest data workers handlers
Referenced by MenuWindow::enter_screen, ZenInfoScreen::enter_screen, ConfigModeScreen::handle_input, SatelliteViewScreen::handle_input, ZenInfoScreen::handle_input, BaseScreenWithMenu::handle_menu_input.
const char * BaseScreen::get_title() const
Get screen name
Referenced by GFXScreen::handle_report.
bool BaseScreen::has_status_bar() const
Get screen name
Referenced by GFXScreen::handle_report.
const __FlashStringHelper * BaseScreen::get_error_message(const worker_map_t &workers, const handler_map_t &handlers) const
Get screen error message (if available), else nullptr
References clamp, SDInterface::i, k_worker_gm_sensor, k_worker_gps_connector, required_gps, required_sd, required_tube, required_wifi, WiFiWrapper::status, STATUS_ERROR_GEIGER, STATUS_ERROR_GPS, STATUS_ERROR_SD, STATUS_ERROR_WIFI_CONNECT_FAILED, STATUS_ERROR_WIFI_CONNECTION_LOST, STATUS_ERROR_WIFI_NO_SSID_AVAIL, WiFiWrapper_i.
Referenced by GFXScreen::handle_report.
const __FlashStringHelper * BaseScreen::get_status_message(const worker_map_t &workers, const handler_map_t &handlers) const
Get screen status message (if available), else nullptr
References clamp, STATUS_MESSAGE_DURATION.
Referenced by GFXScreen::handle_report.
bool BaseScreen::has_required_gps() const
References required_gps.
Referenced by GFXScreen::handle_report.
bool BaseScreen::has_required_sd() const
References required_sd.
Referenced by GFXScreen::handle_report.
bool BaseScreen::has_required_tube() const
References required_tube.
Referenced by GFXScreen::handle_report.
bool BaseScreen::has_required_wifi() const
References required_wifi.
Referenced by GFXScreen::handle_report.
bool BaseScreen::has_required_ble() const
References required_ble.
Referenced by GFXScreen::handle_report.
BaseScreen::BaseScreen(const char *title, bool status_bar)
References clamp.
virtual BaseScreen::~BaseScreen()=default
void BaseScreen::render(const worker_map_t &workers, const handler_map_t &handlers, bool force)
Render the screen with latest data workers handlers
Referenced by do_render.
void BaseScreen::drawButton1(const char *text, ButtonState state=e_button_default) const
References clamp.
Referenced by DebugModeScreen::render, DriveModeScreen::render, FirstTimeStartupScreen::render, SatelliteViewScreen::render, SdMessageScreen::render, SurveyModeScreen::render, BaseScreenWithMenu::render_menu.
void BaseScreen::drawButton2(const char *text, ButtonState state=e_button_default) const
References clamp.
Referenced by DebugModeScreen::render, DriveModeScreen::render, SatelliteViewScreen::render, SdMessageScreen::render, SurveyModeScreen::render, BaseScreenWithMenu::render_menu.
void BaseScreen::drawButton3(const char *text, ButtonState state=e_button_default) const
References clamp.
Referenced by DebugModeScreen::render, DriveModeScreen::render, FirstTimeStartupScreen::render, FixedModeScreen::render, SatelliteViewScreen::render, SdMessageScreen::render, SurveyModeScreen::render, ZenInfoScreen::render, BaseScreenWithMenu::render_menu.
void BaseScreen::clear_screen_content()
Clears page content area (NOT the buttons, status message and status bar)
References clamp, LCD_COLOR_BACKGROUND.
void BaseScreen::set_status_message(const __FlashStringHelper *message)
References clamp.
Referenced by ConfigModeScreen::enter_screen, SatelliteViewScreen::enter_screen, SatelliteViewScreen::handle_input, DriveModeScreen::render, FixedModeScreen::render, SurveyModeScreen::render.
size_t BaseScreen::printFloatFont(float val, int prec, int x, int y, const lgfx::IFont *font)
References clamp.
Referenced by DriveModeScreen::render, FixedModeScreen::render, SurveyModeScreen::render.
size_t BaseScreen::printIntFont(unsigned long val, int x, int y, const lgfx::IFont *font)
References clamp.
Referenced by DriveModeScreen::render, FixedModeScreen::render, SurveyModeScreen::render.
void BaseScreen::drawButton(uint16_t x, const char *text, ButtonState state)