Context
State * Context::current_state
Setup Context::device_setup
Referenced by StateWaitGPSTime::on_exit, StateLogging::process, setup.
GeigerCounter Context::geiger_count
Referenced by loop, on_geiger_counter_available, StateWaitGPSTime::process, StateLogging::process, setup.
GPSSensor Context::gps
Referenced by loop, StateWaitGPSTime::on_exit, on_gps_available, StateWaitGPSTime::process, StateLogging::process.
AXP192& Context::battery_monitor
Referenced by on_geiger_counter_available.
BGeigieLogFormatter Context::bgeigie_formatter
Referenced by on_geiger_counter_available, on_gps_available, StateLogging::process, setup.
SDWrapper Context::sd_wrapper
Referenced by StateLogging::process, setup.
SDLogger Context::logger
Referenced by StateWaitGPSTime::on_exit, StateLogging::process.
Display Context::display
Referenced by loop, on_geiger_counter_available, on_gps_available, setup.
BatteryMonitorIP5306 Context::battery_monitor
StateStartup
StateWaitGPSTime
StateLogging
void Context::setup()
References ConfigData::alarm_level, GeigerCounter::begin, SDWrapper::begin, bgeigie_formatter, clamp, Setup::config, GeigerCounter::configure, ConfigData::cpm2bqm2_factor, ConfigData::cpm2ush_divider, ConfigData::device_id, device_setup, display, Display::feed, geiger_count, Setup::initialize, Setup::load_from_file, SDWrapper::ready, sd_wrapper, BGeigieLogFormatter::set_device_id, SETUP_FILENAME.
Referenced by StateStartup::on_enter.
void Context::on_geiger_counter_available()
References battery_monitor, bgeigie_formatter, GeigerCounter::consume, display, Display::feed, BGeigieLogFormatter::feed, Display::feed_battery_level, geiger_count.
Referenced by StateWaitGPSTime::process, StateLogging::process.
void Context::on_gps_available()
References bgeigie_formatter, display, Display::feed, BGeigieLogFormatter::feed, gps.
Referenced by StateWaitGPSTime::process, StateLogging::process.
void Context::transition_to(State *next_state, bGeigieZen::Event e)
References clamp, State::enter, State::exit.
Referenced by begin, StateStartup::on_enter, StateWaitGPSTime::process.
void Context::setup()
void Context::on_geiger_counter_available()
void Context::on_gps_available()
void Context::transition_to(State *next_state, Event e)
Context::Context()
void Context::begin()
References bGeigieZen::DEVICE_STARTED, StateStartup::instance, transition_to.
Referenced by setup.
void Context::loop()
References clamp, display, geiger_count, gps, State::process, Display::update, GeigerCounter::update, GPSSensor::update.
Referenced by loop.
Context::Context()
void Context::begin()
void Context::loop()