MenuContext
MenuState* MenuContext::current_state
int MenuContext::dimblank_idx
DimBlankTiming MenuContext::dimblank_choices[5][5]
ButtonColors MenuContext::onCol
ButtonColors MenuContext::offCol
Button MenuContext::button_dimblank
Referenced by Display::clear, MenuContext.
Button MenuContext::button_config_network
Referenced by Display::clear, MenuContext.
Display* MenuContext::main_display
Referenced by goto_state, ConfigState::on_entry.
MenuContext::MenuContext()
References button_config_network, button_dimblank.
void MenuContext::goto_state(MenuState *new_state, Display *display)
References clamp, goto_state, main_display.
Referenced by goto_state, Display::update.
void MenuContext::goto_state(MenuState *new_state)
References clamp, MenuState::on_entry, MenuState::on_exit.
void MenuContext::update()
References MenuState::update.
Referenced by Display::update.