BGeigieLogFormatter
char BGeigieLogFormatter::_buffer[LOG_BUFFER_SIZE]
int BGeigieLogFormatter::_device_id
bool BGeigieLogFormatter::_geiger_fresh
bool BGeigieLogFormatter::_gps_fresh
uint32_t BGeigieLogFormatter::_cpm
uint32_t BGeigieLogFormatter::_cpb
uint32_t BGeigieLogFormatter::_total_count
char BGeigieLogFormatter::_geiger_status
int BGeigieLogFormatter::_year
int BGeigieLogFormatter::_month
int BGeigieLogFormatter::_day
int BGeigieLogFormatter::_hour
int BGeigieLogFormatter::_minute
int BGeigieLogFormatter::_second
char BGeigieLogFormatter::_lat[10]
char BGeigieLogFormatter::_NS
char BGeigieLogFormatter::_lon[11]
char BGeigieLogFormatter::_WE
float BGeigieLogFormatter::_altitude
float BGeigieLogFormatter::_precision
int BGeigieLogFormatter::_satellites
char BGeigieLogFormatter::_gps_status
BGeigieLogFormatter::BGeigieLogFormatter(uint32_t device_id)
BGeigieLogFormatter::BGeigieLogFormatter()
void BGeigieLogFormatter::set_device_id(uint32_t device_id)
Referenced by Context::setup.
void BGeigieLogFormatter::feed(GPSSensor &gps)
References clamp, gps.
Referenced by Context::on_geiger_counter_available, Context::on_gps_available.
void BGeigieLogFormatter::feed(const GeigerCounter &geiger_count)
References GeigerCounter::per_bin, GeigerCounter::per_minute_raw, GeigerCounter::total, GeigerCounter::valid.
bool BGeigieLogFormatter::ready()
Referenced by StateLogging::process.
const char * BGeigieLogFormatter::format()
References checksum, clamp, DEVICE_HEADER, LOG_BUFFER_SIZE.
Referenced by StateLogging::process.
BGeigieLogFormatter::BGeigieLogFormatter(uint32_t device_id)
BGeigieLogFormatter::BGeigieLogFormatter()
void BGeigieLogFormatter::set_device_id(uint32_t device_id)
void BGeigieLogFormatter::feed(GPSSensor &gps)
void BGeigieLogFormatter::feed(const GeigerCounter &geiger_count)
bool BGeigieLogFormatter::ready()
const char * BGeigieLogFormatter::format()