GPSSensor
const uint32_t GPSSensor::_timeout
HardwareSerial GPSSensor::ss
TinyGPSPlus GPSSensor::_data
GPSState GPSSensor::_state
bool GPSSensor::_available
uint32_t GPSSensor::_last_update_millis
bool GPSSensor::_never_fixed
bool GPSSensor::_has_fix
bool GPSSensor::_time_valid
void GPSSensor::_update_fix_metadata()
void GPSSensor::_update_fix_metadata()
GPSSensor::GPSSensor(int serial_number, uint32_t baud_rate)
References clamp, ss.
uint32_t GPSSensor::age_ms() const
References clamp.
Referenced by update.
bool GPSSensor::has_started() const
References GPS_Startup.
bool GPSSensor::is_updating() const
References GPS_Idle.
bool GPSSensor::available() const
Referenced by StateWaitGPSTime::process, StateLogging::process.
void GPSSensor::update()
References age_ms, clamp, TinyGPSPlus::encode, GPS_Got_GPGGA_Wait_GPRMC, GPS_Got_GPRMC_Wait_GPGGA, GPS_Idle, GPS_Startup, GPS_Wait_GPGGA_Wait_GPRMC.
Referenced by Context::loop.
bool GPSSensor::has_fix() const
bool GPSSensor::never_fixed() const
bool GPSSensor::time_valid() const
Referenced by StateWaitGPSTime::process.
TinyGPSPlus & GPSSensor::data()
Referenced by StateWaitGPSTime::on_exit, StateLogging::process.
const TinyGPSPlus & GPSSensor::data() const
References data.
Referenced by data.
GPSSensor::GPSSensor(int serial_number, uint32_t baud_rate)
References clamp, ss.
uint32_t GPSSensor::age_ms() const
References clamp.
bool GPSSensor::has_started() const
References GPS_Startup.
bool GPSSensor::is_updating() const
References GPS_Idle.
bool GPSSensor::available() const
void GPSSensor::update()
bool GPSSensor::has_fix() const
bool GPSSensor::never_fixed() const
bool GPSSensor::time_valid() const
TinyGPSPlus & GPSSensor::data()
const TinyGPSPlus & GPSSensor::data() const
References data.
Referenced by data.