SDInterface
SdStatus
SdError
SdStatus SDInterface::_status
uint32_t SDInterface::_device_id
uint32_t SDInterface::_last_read
uint32_t SDInterface::_last_write
uint32_t SDInterface::_last_try
SDInterface::SDInterface(const SDInterface &)=delete
SDInterface & SDInterface::operator=(const SDInterface &)=delete
SDInterface::SDInterface(SDInterface &&)=delete
SDInterface & SDInterface::operator=(SDInterface &&)=delete
bool SDInterface::ready()
Checks sd readiness, will end sd connection if sd has been lost true if ready
References clamp, e_sd_config_status_not_ready, end, TEST_FILENAME.
Referenced by begin, clear_all_logs, delete_log, SdLogger::handle_produced_work, has_safezen_content, log_println, read_safezen_file_to_settings, rename_log, write_safezen_file_from_settings.
bool SDInterface::can_write_logs() const
Eeturns true if sd was properly set up with device id and all.. true if ready
References e_sd_config_status_ok.
Referenced by GFXScreen::handle_report.
SDInterface::SdStatus SDInterface::status() const
last know status
Referenced by SdMessageScreen::enter_screen, DriveModeScreen::render, SurveyModeScreen::render.
bool SDInterface::begin()
We note that for the ESP32, the SD library is robust to multiple call to the begin() function true if available We note that for the ESP32, the SD library is robust to multiple call to the begin() function true if ready
References clamp, e_sd_config_status_config_no_content, e_sd_config_status_not_ready, ready, SD_CS_PIN, TEST_FILENAME.
bool SDInterface::clear_all_logs()
Delete all log files / directories true if available
References DRIVE_LOG_DIRECTORY, JOURNAL_LOG_DIRECTORY, ready, SURVEY_LOG_DIRECTORY.
Referenced by Controller::factory_reset.
bool SDInterface::just_wrote() const
true last write in last 0.5 sec
References clamp.
Referenced by GFXScreen::handle_report.
void SDInterface::end()
close SD connection
References clamp, e_sd_config_status_not_ready.
Referenced by log_println, ready, setup_log, write_safezen_file_from_settings.
bool SDInterface::setup_log(const char *dir, const char *log_name_output, bool clear_on_exist)
References clamp, end.
bool SDInterface::rename_log(const char *old_log_name, const char *new_log_name)
Rename log file
References clamp, ready.
Referenced by SdLogger::handle_produced_work.
bool SDInterface::delete_log(const char *log_name)
Delete log file
References clamp, ready.
Referenced by SdLogger::deactivate.
bool SDInterface::log_println(const char *log_name, const char *data)
References clamp, end, ready.
Referenced by SdLogger::activate.
SDInterface::SdStatus SDInterface::has_safezen_content(uint16_t device_id)
Get device id from SAFEZEN.txt file on the SD card device id if available, else 0
References clamp, e_sd_config_status_config_different_id, e_sd_config_status_config_no_content, e_sd_config_status_no_config_file, e_sd_config_status_not_ready, e_sd_config_status_ok, ready, sd_config_device_id_f, SD_CONFIG_FIELD_DEVICE_ID, SETUP_FILENAME.
bool SDInterface::read_safezen_file_to_settings(LocalStorage &settings)
Read SAFEZEN.txt file contents on SD card to local storage true if succeeded
References clamp, CONFIG_VAL_MAX, ready, SD_CONFIG_FIELD_VERSION, sd_config_version_f, settings, SETUP_FILENAME, VERSION_NUMBER.
Referenced by Controller::load_sd_config.
bool SDInterface::write_safezen_file_from_settings(const LocalStorage &settings, bool full=false)
Write SAFEZEN.txt file on the SD card from local storage true if succeeded
References clamp, e_sd_config_status_ok, end, LocalStorage::get_alert_threshold, LocalStorage::get_ap_password, LocalStorage::get_api_key, LocalStorage::get_cpm_usvh, LocalStorage::get_device_id, LocalStorage::get_dop_max, LocalStorage::get_enable_journal, LocalStorage::get_fixed_latitude, LocalStorage::get_fixed_longitude, LocalStorage::get_fixed_range, LocalStorage::get_log_void, LocalStorage::get_manual_logging, LocalStorage::get_wifi_password, LocalStorage::get_wifi_ssid, ready, sd_config_access_point_password_write_f, sd_config_alert_threshold_f, sd_config_api_key_f, sd_config_cpm_usvh_f, sd_config_device_id_f, sd_config_dop_max_f, sd_config_enable_journal_f, sd_config_fixed_latitude_f, sd_config_fixed_longitude_f, sd_config_fixed_range_f, sd_config_log_void_f, sd_config_manual_logging_f, sd_config_version_f, sd_config_wifi_password_write_f, sd_config_wifi_ssid_write_f, settings, SETUP_FILENAME, VERSION_NUMBER.
Referenced by Controller::write_sd_config.
static SDInterface & SDInterface::i()
Singleton
References clamp.
Referenced by SdLogger::activate, SdLogger::deactivate, SdMessageScreen::enter_screen, Controller::factory_reset, BaseScreen::get_error_message, SdLogger::handle_produced_work, GFXScreen::handle_report, Controller::load_sd_config, DriveModeScreen::render, SurveyModeScreen::render, Controller::write_sd_config.
SDInterface::SDInterface()
bool SDInterface::read_safezen_file_latest(LocalStorage &settings, File &file)
Read SAFEZEN.txt file contents on SD card to local storage true if succeeded
void SDInterface::delete_directory(const char *dirPath)