HardwareCounter
uint32_t HardwareCounter::_delay_s
int HardwareCounter::_gpio
pcnt_unit_t HardwareCounter::_unit
const int16_t HardwareCounter::_max_value
uint32_t HardwareCounter::_n_wraparound
uint32_t HardwareCounter::_start_time
uint32_t HardwareCounter::_last_count
bool HardwareCounter::_available
Ticker HardwareCounter::_timer
CircularBuffer<uint32_t, PULSE_COUNT_BUFFER_MAX> HardwareCounter::_count_buffer
uint32_t HardwareCounter::_get_count_reset()
uint32_t HardwareCounter::_get_count_reset()
uint32_t HardwareCounter::_get_count_reset()
void timer_intr_handler(void *arg)
Referenced by begin.
void timer_intr_handler(void *arg)
void timer_intr_handler(void *arg)
HardwareCounter::HardwareCounter()
HardwareCounter::HardwareCounter(uint32_t delay_s, int gpio, pcnt_unit_t unit=PCNT_UNIT_0)
uint32_t HardwareCounter::get_last_count()
Referenced by GeigerCounter::activate, GeigerCounter::produce_data, GeigerCounter::update.
void HardwareCounter::begin()
References clamp, pcnt_intr_handler, reset, timer_intr_handler.
Referenced by GeigerCounter::activate, GeigerCounter::begin.
void HardwareCounter::reset()
References clamp.
Referenced by begin.
bool HardwareCounter::available()
Referenced by GeigerCounter::activate, GeigerCounter::produce_data, GeigerCounter::update.
HardwareCounter::HardwareCounter()
HardwareCounter::HardwareCounter(uint32_t delay_s, int gpio, pcnt_unit_t unit=PCNT_UNIT_0)
uint32_t HardwareCounter::get_last_count()
void HardwareCounter::begin()
void HardwareCounter::reset()
bool HardwareCounter::available()
HardwareCounter::HardwareCounter()
uint32_t HardwareCounter::get_last_count()
void HardwareCounter::begin()
void HardwareCounter::reset()
bool HardwareCounter::available() const
References CircularBuffer< T, max >::empty.