Display
static const int Display::width
static const int Display::height
uint32_t Display::_refresh_period_ms
bool Display::dimming_enabled
bool Display::display_dimmed
uint32_t Display::delay_dimming
uint32_t Display::delay_blanking
RBD::Timer Display::timer_dimming
RBD::Timer Display::timer_blanking
Button Display::dimmingButton
bGeigieZen::DisplayState Display::state
MotionDetect Display::mpu
DisplayData Display::data
Referenced by draw_main, draw_menu, draw_qrcode, draw_survey, feed, feed, feed, feed_battery_level.
WiFiConnection Display::wificonn
ConfigWebServer Display::webserver
Referenced by ConfigState::on_entry.
Display::Display(uint32_t refresh_period_ms)
void Display::clear()
References MenuContext::button_config_network, MenuContext::button_dimblank, clamp, core2Brightness, LEVEL_BRIGHT, mcontext.
Referenced by update.
void Display::feed(const GeigerCounter &geiger_count)
References data, DisplayData::geiger_cpm, DisplayData::geiger_fresh, DisplayData::geiger_uSv, DisplayData::geiger_valid, GeigerCounter::per_minute, GeigerCounter::uSv, GeigerCounter::valid.
Referenced by Context::on_geiger_counter_available, Context::on_gps_available, Context::setup.
void Display::feed(GPSSensor &geiger_count)
References TinyGPSPlus::altitude, TinyGPSPlus::course, data, TinyGPSPlus::date, gps, DisplayData::gps_altitude, DisplayData::gps_course, DisplayData::gps_date, DisplayData::gps_fresh, DisplayData::gps_location, DisplayData::gps_satellites, DisplayData::gps_speed, DisplayData::gps_time, TinyGPSPlus::location, TinyGPSPlus::satellites, TinyGPSPlus::speed, TinyGPSPlus::time.
void Display::feed(const Setup &device_setup)
References Setup::config, data, DisplayData::device_id, ConfigData::device_id.
void Display::feed_battery_level(int8_t level)
References DisplayData::battery_level, clamp, data.
Referenced by Context::on_geiger_counter_available.
void Display::update()
References clamp, clear, core2Brightness, draw_base, draw_main, draw_qrcode, draw_survey, MenuContext::goto_state, inactivestate, LEVEL_BLANKED, LEVEL_BRIGHT, LEVEL_DIMMED, mcontext, MotionDetect::motionDetected, mstate, bGeigieZen::S_BLANKED, bGeigieZen::S_MAIN_DRAW, bGeigieZen::S_MAIN_SHOW, bGeigieZen::S_MENU_DRAW, bGeigieZen::S_MENU_SHOW, bGeigieZen::S_QRCODE_DRAW, bGeigieZen::S_QRCODE_SHOW, bGeigieZen::S_STARTUP, bGeigieZen::S_SURVEY_BLANKED, bGeigieZen::S_SURVEY_DRAW, bGeigieZen::S_SURVEY_SHOW, MenuContext::update.
Referenced by Context::loop.
void Display::draw_base()
References clamp.
Referenced by update.
void Display::draw_navbar(const char *A, const char *B, const char *C)
References clamp, draw_navbar_label.
Referenced by draw_main, draw_menu, draw_survey.
void Display::draw_navbar_label(const char *s, const Button &b)
References clamp.
Referenced by draw_navbar.
void Display::draw_main()
References DisplayData::battery_level, clamp, data, TinyGPSCourse::deg, DisplayData::device_id, draw_navbar, DisplayData::geiger_cpm, DisplayData::geiger_fresh, DisplayData::geiger_uSv, DisplayData::geiger_valid, DisplayData::gps_altitude, DisplayData::gps_course, DisplayData::gps_date, DisplayData::gps_fresh, DisplayData::gps_location, DisplayData::gps_satellites, DisplayData::gps_speed, DisplayData::gps_time, TinyGPSLocation::isValid, TinyGPSDecimal::isValid, TinyGPSInteger::isValid, TinyGPSSpeed::kmph, TinyGPSLocation::lat, TinyGPSLocation::lng, TinyGPSAltitude::meters, printDate, printFloat, printFloatFont, printInt, printIntFont, printTime, showBatteryLevel, showDeviceId, TinyGPSInteger::value.
Referenced by update.
void Display::draw_qrcode()
References clamp, data, DisplayData::device_id, QR_CODE_DEV_ID_NDIGITS, QR_CODE_URL_BASE.
Referenced by update.
void Display::draw_survey()
References DisplayData::battery_level, clamp, data, DisplayData::device_id, draw_navbar, DisplayData::geiger_bqm2, DisplayData::geiger_cpm, DisplayData::geiger_fresh, DisplayData::geiger_uSv, DisplayData::geiger_valid, DisplayData::gps_altitude, DisplayData::gps_date, DisplayData::gps_fresh, DisplayData::gps_location, DisplayData::gps_satellites, DisplayData::gps_time, TinyGPSLocation::isValid, TinyGPSDecimal::isValid, TinyGPSInteger::isValid, TinyGPSLocation::lat, TinyGPSLocation::lng, TinyGPSAltitude::meters, printDate, printFloat, printFloatFont, printInt, printIntFont, printTime, showBatteryLevel, showDeviceId, TinyGPSInteger::value.
Referenced by update.
void Display::draw_menu()
References DisplayData::battery_level, clamp, data, DisplayData::device_id, draw_navbar, showBatteryLevel, showDeviceId.
void Display::showDeviceId(uint32_t id, int16_t x=10, int16_t y=30)
References clamp.
Referenced by draw_main, draw_menu, draw_survey.
void Display::showBatteryLevel(float level, int16_t x=270, int16_t y=30)
References clamp.
Referenced by draw_main, draw_menu, draw_survey.
void Display::set_dimblank_delays(uint32_t dimdelay, uint32_t blankdelay)
References clamp.
Display::Display(uint32_t refresh_period_ms)
void Display::clear()
void Display::feed(const GeigerCounter &geiger_count)
void Display::feed(GPSSensor &geiger_count)
void Display::feed(const Setup &device_setup)
References Setup::config, data, DisplayData::device_id, ConfigData::device_id.
void Display::feed_battery_level(int8_t level)
References DisplayData::battery_level, clamp, data.
void Display::update()
void Display::draw_base()
void Display::draw_navbar(const char *A, const char *B, const char *C)
void Display::draw_main()
void Display::draw_qrcode()