SDWrapper
bool SDWrapper::_sd_ready
SDWrapper::SDWrapper()
bool SDWrapper::ready()
Referenced by StateLogging::process, Context::setup.
bool SDWrapper::begin()
References clamp, SD_CS_PIN.
Referenced by Context::setup.
SDWrapper::SDWrapper()
bool SDWrapper::ready()
bool SDWrapper::begin()
References clamp, SD_CS_PIN.