SDLogger
bool SDLogger::_folder_created
bool SDLogger::_logfile_created
bool SDLogger::_ready
char SDLogger::_filename[filename_maxlen]
static const size_t SDLogger::filename_maxlen
SDLogger::SDLogger()
bool SDLogger::start(uint32_t device_id, uint16_t year, uint8_t month, uint8_t day)
References clamp, device_nickname, log, LOG_HEADER_LINE1, LOG_HEADER_LINE2, LOG_HEADER_LINE3, MAJOR, MINOR, PATCH, ready.
Referenced by StateWaitGPSTime::on_exit, StateLogging::process.
bool SDLogger::ready() const
Referenced by StateLogging::process, start.
bool SDLogger::folder_created() const
Referenced by StateLogging::process.
bool SDLogger::log(const char *log_line) const
References clamp.
Referenced by StateLogging::process, start.
SDLogger::SDLogger()
bool SDLogger::start(uint32_t device_id, uint16_t year, uint8_t month, uint8_t day)
bool SDLogger::ready() const
bool SDLogger::folder_created() const
bool SDLogger::log(const char *log_line) const