LocalStorage
OperationalMode
Preferences LocalStorage::_memory
uint16_t LocalStorage::_device_id
uint16_t LocalStorage::_alert_threshold
bool LocalStorage::_cpm_usvh
bool LocalStorage::_manual_logging
bool LocalStorage::_enable_journal
bool LocalStorage::_log_void
uint16_t LocalStorage::_screen_dim_timeout
uint16_t LocalStorage::_screen_off_timeout
bool LocalStorage::_animated_screensaver
char LocalStorage::_ap_password[CONFIG_VAL_MAX][CONFIG_VAL_MAX]
char LocalStorage::_wifi_ssid[CONFIG_VAL_MAX][CONFIG_VAL_MAX]
char LocalStorage::_wifi_password[CONFIG_LONG_VAL_MAX][CONFIG_LONG_VAL_MAX]
char LocalStorage::_api_key[CONFIG_VAL_MAX][CONFIG_VAL_MAX]
double LocalStorage::_fixed_longitude
double LocalStorage::_fixed_latitude
float LocalStorage::_fixed_range
uint16_t LocalStorage::_dop_max
OperationalMode LocalStorage::_last_mode
double LocalStorage::_last_longitude
double LocalStorage::_last_latitude
LocalStorage::LocalStorage()
virtual LocalStorage::~LocalStorage()=default
void LocalStorage::reset_defaults()
Reset settings to default (defined in user_config)
References clamp, clear, D_ALARM_THRESHOLD, D_ANIMATED_SCREENSAVER, D_AP_PASSWORD, D_API_KEY, D_CPM_USVH, D_DEVICE_ID, D_DOP_MAX, D_ENABLE_JOURNAL, D_FIXED_LATITUDE, D_FIXED_LONGITUDE, D_FIXED_RANGE, D_LAST_LATITUDE, D_LAST_LONGITUDE, D_LOG_VOID, D_MANUAL_LOGGING, D_SCREEN_DIM_TIMEOUT, D_SCREEN_OFF_TIMEOUT, D_WIFI_PASSWORD, D_WIFI_SSID, e_operational_mode_drive, set_alert_threshold, set_animated_screensaver, set_ap_password, set_api_key, set_cpm_usvh, set_device_id, set_dop_max, set_enable_journal, set_fixed_latitude, set_fixed_longitude, set_fixed_range, set_last_latitude, set_last_longitude, set_last_mode, set_log_void, set_manual_logging, set_screen_dim_timeout, set_screen_off_timeout, set_wifi_password, set_wifi_ssid.
Referenced by Controller::reset_settings.
uint16_t LocalStorage::get_device_id() const final
Referenced by BluetoothReporter::activate, ConfigWebServer::add_urls, ConfigModeScreen::enter_screen, HttpPages::get_config_connection_page, HttpPages::get_config_device_page, HttpPages::get_config_location_page, HttpPages::get_home_page, BootScreen::handle_input, GFXScreen::handle_report, LogAggregator::produce_data, FirstTimeStartupScreen::render, SDInterface::write_safezen_file_from_settings.
uint32_t LocalStorage::get_fixed_device_id() const final
Referenced by HttpPages::get_home_page, ApiConnector::handle_produced_work, ApiConnector::reading_to_json.
const char * LocalStorage::get_ap_password() const final
Referenced by ConfigWebServer::add_urls, ConfigModeScreen::enter_screen, HttpPages::get_config_connection_page, SDInterface::write_safezen_file_from_settings.
uint16_t LocalStorage::get_alert_threshold() const final
Referenced by HttpPages::get_config_device_page, ApiConnector::handle_produced_work, SDInterface::write_safezen_file_from_settings.
bool LocalStorage::get_cpm_usvh() const final
Referenced by HttpPages::get_config_device_page, DriveModeScreen::render, FixedModeScreen::render, SurveyModeScreen::render, SDInterface::write_safezen_file_from_settings.
bool LocalStorage::get_manual_logging() const final
Referenced by DriveModeScreen::enter_screen, SurveyModeScreen::enter_screen, HttpPages::get_config_device_page, SDInterface::write_safezen_file_from_settings.
bool LocalStorage::get_enable_journal() const final
Referenced by HttpPages::get_config_device_page, SDInterface::write_safezen_file_from_settings.
bool LocalStorage::get_log_void() const final
Referenced by HttpPages::get_config_device_page, SdLogger::handle_produced_work, SDInterface::write_safezen_file_from_settings.
uint16_t LocalStorage::get_screen_dim_timeout() const final
Referenced by HttpPages::get_config_device_page, GFXScreen::handle_report.
uint16_t LocalStorage::get_screen_off_timeout() const final
Referenced by HttpPages::get_config_device_page, GFXScreen::handle_report.
bool LocalStorage::get_animated_screensaver() const final
Referenced by HttpPages::get_config_device_page.
const char * LocalStorage::get_wifi_ssid() const final
Referenced by ApiConnector::activate, ConfigWebServer::add_urls, ConfigModeScreen::enter_screen, HttpPages::get_config_connection_page, SDInterface::write_safezen_file_from_settings.
const char * LocalStorage::get_wifi_password() const final
Referenced by ApiConnector::activate, ConfigWebServer::add_urls, ConfigModeScreen::enter_screen, HttpPages::get_config_connection_page, SDInterface::write_safezen_file_from_settings.
const char * LocalStorage::get_api_key() const final
Referenced by ConfigWebServer::add_urls, HttpPages::get_config_connection_page, ApiConnector::handle_async, SDInterface::write_safezen_file_from_settings.
double LocalStorage::get_fixed_longitude() const final
Referenced by HttpPages::get_config_location_page, LogAggregator::produce_data, ApiConnector::reading_to_json, FixedModeScreen::render, SDInterface::write_safezen_file_from_settings.
double LocalStorage::get_fixed_latitude() const final
Referenced by HttpPages::get_config_location_page, LogAggregator::produce_data, ApiConnector::reading_to_json, FixedModeScreen::render, SDInterface::write_safezen_file_from_settings.
float LocalStorage::get_fixed_range() const final
Referenced by HttpPages::get_config_location_page, LogAggregator::produce_data, SDInterface::write_safezen_file_from_settings.
uint16_t LocalStorage::get_dop_max() const final
Referenced by HttpPages::get_config_location_page, LogAggregator::produce_data, SDInterface::write_safezen_file_from_settings.
double LocalStorage::get_last_longitude() const final
Referenced by ConfigWebServer::add_urls, HttpPages::get_config_location_page.
double LocalStorage::get_last_latitude() const final
Referenced by ConfigWebServer::add_urls, HttpPages::get_config_location_page.
LocalStorage::OperationalMode LocalStorage::get_last_mode() const final
Referenced by DefaultEntryScreen::handle_input.
void LocalStorage::set_device_id(uint16_t device_id, bool force)
References clamp, key_device_id, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_ap_password(const char *ap_password, bool force)
References clamp, CONFIG_VAL_MAX, key_ap_password, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_alert_threshold(uint16_t alert_threshold, bool force)
References clamp, key_alert_threshold, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_cpm_usvh(bool cpm_usvh, bool force)
References clamp, key_cpm_usvh, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_manual_logging(bool manual_logging, bool force)
References clamp, key_manual_logging, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_enable_journal(bool enable_journal, bool force)
References clamp, key_enable_journal, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_log_void(bool log_void, bool force)
References clamp, key_log_void, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_screen_dim_timeout(uint16_t screen_dim_timeout, bool force)
References clamp, key_screen_dim_timeout, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_screen_off_timeout(uint16_t screen_off_timeout, bool force)
References clamp, key_screen_off_timeout, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_animated_screensaver(bool animated_screensaver, bool force)
References clamp, key_animated_screensaver, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_wifi_ssid(const char *wifi_ssid, bool force)
References clamp, CONFIG_VAL_MAX, key_wifi_ssid, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_wifi_password(const char *wifi_password, bool force)
References clamp, CONFIG_LONG_VAL_MAX, key_wifi_password, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_api_key(const char *api_key, bool force)
References clamp, CONFIG_VAL_MAX, key_api_key, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_fixed_longitude(double fixed_longitude, bool force)
References clamp, key_fixed_longitude, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_fixed_latitude(double fixed_latitude, bool force)
References clamp, key_fixed_latitude, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_fixed_range(float fixed_range, bool force)
References clamp, key_fixed_range, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_dop_max(uint16_t dop_max, bool force)
References clamp, key_dop_max, memory_name.
Referenced by reset_defaults.
void LocalStorage::set_last_longitude(double last_longitude, bool force)
References clamp, key_last_longitude, memory_name.
Referenced by produce_data, reset_defaults.
void LocalStorage::set_last_latitude(double last_latitude, bool force)
References clamp, key_last_latitude, memory_name.
Referenced by produce_data, reset_defaults.
void LocalStorage::set_last_mode(OperationalMode last_mode, bool force)
References clamp, key_last_mode, memory_name.
Referenced by GFXScreen::handle_report, reset_defaults.
bool LocalStorage::clear()
References clamp, memory_name.
Referenced by reset_defaults.
bool LocalStorage::activate(bool) override
Read all settings
References clamp, CONFIG_VAL_MAX, D_ALARM_THRESHOLD, D_ANIMATED_SCREENSAVER, D_AP_PASSWORD, D_API_KEY, D_CPM_USVH, D_DEVICE_ID, D_DOP_MAX, D_ENABLE_JOURNAL, D_FIXED_LATITUDE, D_FIXED_LONGITUDE, D_FIXED_RANGE, D_LAST_LATITUDE, D_LAST_LONGITUDE, D_LOG_VOID, D_MANUAL_LOGGING, D_SCREEN_DIM_TIMEOUT, D_SCREEN_OFF_TIMEOUT, D_WIFI_PASSWORD, D_WIFI_SSID, e_operational_mode_drive, key_alert_threshold, key_animated_screensaver, key_ap_password, key_api_key, key_cpm_usvh, key_device_id, key_dop_max, key_enable_journal, key_fixed_latitude, key_fixed_longitude, key_fixed_range, key_last_latitude, key_last_longitude, key_last_mode, key_log_void, key_manual_logging, key_screen_dim_timeout, key_screen_off_timeout, key_wifi_password, key_wifi_ssid, memory_name.
int8_t LocalStorage::produce_data(const worker_map_t &workers) override
References clamp, gps, k_worker_gps_connector, set_last_latitude, set_last_longitude.