Controller
bool Controller::_initialized
LocalStorage& Controller::_settings
TeenyUbloxConnect& Controller::_gnss
Controller::Controller(LocalStorage &settings, TeenyUbloxConnect &gnss)
References DeviceState::e_mode_not_set, SDInterface::e_sd_config_status_not_ready.
virtual Controller::~Controller()=default
void Controller::initialize() override
void Controller::start_default_workers()
Starts default workers and handlers, loads SD
References clamp, k_worker_battery_indicator, k_worker_button_1, k_worker_button_2, k_worker_button_3, k_worker_device_state, k_worker_gm_sensor, k_worker_gps_connector, k_worker_local_storage, k_worker_log_aggregator, k_worker_rtc_connector.
Referenced by setup.
bool Controller::load_sd_config()
Load SD config into device memory
References SDInterface::i, SDInterface::read_safezen_file_to_settings.
Referenced by ConfigModeScreen::enter_screen, FirstTimeStartupScreen::enter_screen, SdMessageScreen::handle_input.
bool Controller::write_sd_config()
Writes device settings onto SD
References SDInterface::i, SDInterface::write_safezen_file_from_settings.
Referenced by ConfigModeScreen::enter_screen, SdMessageScreen::handle_input.
bool Controller::factory_reset()
Clears device memory, clears settings on the SD card, clears log files
References SDInterface::clear_all_logs, SDInterface::i, reset_settings.
Referenced by ConfigModeScreen::handle_input.
TeenyUbloxConnect & Controller::get_gnss()
get GNSS instance
Referenced by SatelliteViewScreen::enter_screen.
void Controller::reset_settings()
Reset memory settings and restart system
References LocalStorage::reset_defaults.
Referenced by factory_reset, ConfigModeScreen::handle_input.
const LocalStorage & Controller::get_settings() const
Referenced by ConfigModeScreen::enter_screen, DriveModeScreen::enter_screen, SurveyModeScreen::enter_screen.
int8_t Controller::produce_data() override
As a worker, the controller will notify of any state changes