MenuWindow
MenuWindow::MenuWindow()
BaseScreen * MenuWindow::handle_input(Controller &controller, const worker_map_t &workers) override
References clamp, controller, BaseScreenWithMenu::handle_menu_input, MAIN_MENU_ITEMS, MAIN_MENU_MAX.
Referenced by GFXScreen::handle_report.
void MenuWindow::enter_screen(Controller &controller) override
Enter the screen, use controller to enable screen specific workers/handlers controller
References BaseScreen::force_next_render, BaseScreenWithMenu::open_menu.
Referenced by GFXScreen::handle_report.
void MenuWindow::leave_screen(Controller &controller) override
Leave the screen, use controller to disable screen specific workers/handlers controller
References BaseScreenWithMenu::open_menu.
Referenced by GFXScreen::handle_report.
void MenuWindow::render(const worker_map_t &workers, const handler_map_t &handlers, bool force) override
Render the screen with latest data workers handlers
References clamp, MAIN_MENU_ITEMS, MAIN_MENU_MAX, BaseScreenWithMenu::menu_open, BaseScreenWithMenu::render_menu.