Measurement
bool Measurement< T >::_available
void Measurement< T >::set_avalaible()
void Measurement< T >::unset_avalaible()
void Measurement< T >::set_avalaible()
void Measurement< T >::unset_avalaible()
virtual void Measurement< T >::init()=0
virtual bool Measurement< T >::available()
Referenced by Aggregator::update.
virtual bool Measurement< T >::prepare_data(T &dest)=0
Referenced by Measurement< T >::get_data.
bool Measurement< T >::get_data(T &dest)
References clamp, Measurement< T >::prepare_data.
Referenced by Aggregator::update.
virtual void Measurement< T >::init()=0
virtual bool Measurement< T >::available()
virtual bool Measurement< T >::prepare_data(T &dest)=0
bool Measurement< T >::get_data(T &dest)
References clamp, Measurement< T >::prepare_data.