State
Context * State::_ctx
Referenced by enter, enter, exit, exit, StateStartup::on_enter, StateWaitGPSTime::on_exit, StateWaitGPSTime::process, StateLogging::process.
State::State()
void State::enter(Context *ctx, bGeigieZen::Event e)
References _ctx, clamp, on_enter.
Referenced by Context::transition_to.
void State::exit(bGeigieZen::Event e)
References _ctx, clamp, on_exit.
Referenced by Context::transition_to.
virtual void State::on_enter(bGeigieZen::Event e)=0
Referenced by enter, enter.
virtual void State::process()=0
Referenced by Context::loop.
virtual void State::on_exit(bGeigieZen::Event e)=0
Referenced by exit, exit.
State::State()
void State::enter(Context *ctx, Event e)
References _ctx, clamp, on_enter.
void State::exit(Event e)
References _ctx, clamp, on_exit.
virtual void State::on_enter(Event e)=0
virtual void State::process()=0
virtual void State::on_exit(Event e)=0