HttpPages
const uint8_t HttpPages::pure_css[PURE_CSS_SIZE]
Gzipped pure css library https://purecss.io/
Referenced by ConfigWebServer::add_urls.
const uint8_t HttpPages::favicon[FAVICON_SIZE]
Referenced by ConfigWebServer::add_urls.
const char * HttpPages::pure_js
bool HttpPages::internet_access
Referenced by ConfigWebServer::activate, ConfigWebServer::produce_data.
char HttpPages::transmission_buffer[TRANSMISSION_SIZE]
HttpPages::HttpPages()=delete
const char * HttpPages::get_home_page(const LocalStorage &settings)
Render the home page device_id : To display the device id on the page complete page rendered
References clamp, FIXED_MODE_GRAFANA_URL, LocalStorage::get_device_id, LocalStorage::get_fixed_device_id, settings, TITLE_HOME, VERSION_NUMBER.
Referenced by ConfigWebServer::add_urls.
const char * HttpPages::get_config_device_page(bool display_success, const LocalStorage &settings)
Render the configuration page for device settings display_success device_id led_intensity colorblind complete page rendered
References clamp, FORM_NAME_ALERT_THRESHOLD, FORM_NAME_ANIMATED_SCREENSAVER, FORM_NAME_CPM_USVH, FORM_NAME_ENABLE_JOURNAL, FORM_NAME_LOG_VOID, FORM_NAME_MANUAL_LOGGING, FORM_NAME_SCREEN_DIM_TIMEOUT, FORM_NAME_SCREEN_OFF_TIMEOUT, LocalStorage::get_alert_threshold, LocalStorage::get_animated_screensaver, LocalStorage::get_cpm_usvh, LocalStorage::get_device_id, LocalStorage::get_enable_journal, LocalStorage::get_log_void, LocalStorage::get_manual_logging, LocalStorage::get_screen_dim_timeout, LocalStorage::get_screen_off_timeout, settings, success_message, TITLE_CONF_DEVICE.
Referenced by ConfigWebServer::add_urls.
const char * HttpPages::get_config_connection_page(bool display_success, const LocalStorage &settings)
Render the configuration page for connection settings display_success device_id device_password wifi_ssid wifi_password api_key use_dev complete page rendered
References ACCESS_POINT_SSID, clamp, FORM_NAME_AP_LOGIN, FORM_NAME_API_KEY, FORM_NAME_WIFI_PASS, FORM_NAME_WIFI_SSID, LocalStorage::get_ap_password, LocalStorage::get_api_key, LocalStorage::get_device_id, LocalStorage::get_wifi_password, LocalStorage::get_wifi_ssid, settings, success_message, TITLE_CONF_CONNECTION.
Referenced by ConfigWebServer::add_urls.
const char * HttpPages::get_config_location_page(bool display_success, const LocalStorage &settings)
Render the configuration page for location settings display_success device_id use_home_location home_latitude home_longitude last_latitude last_longitude complete page rendered
References clamp, FORM_NAME_DOP_MAX, FORM_NAME_FIXED_RANGE, FORM_NAME_LOC_FIXED_LAT, FORM_NAME_LOC_FIXED_LON, LocalStorage::get_device_id, LocalStorage::get_dop_max, LocalStorage::get_fixed_latitude, LocalStorage::get_fixed_longitude, LocalStorage::get_fixed_range, LocalStorage::get_last_latitude, LocalStorage::get_last_longitude, settings, success_message, TITLE_CONF_LOCATION.
Referenced by ConfigWebServer::add_urls.
const char * HttpPages::render_full_page(uint32_t device_id, const char *page_name, const char *content_format,...)