MenuState
MenuContext* MenuState::mcontext_
virtual MenuState::~MenuState()
void MenuState::set_context(MenuContext *context)
References context.
virtual void MenuState::on_entry(MenuContext *context)=0
Referenced by MenuContext::goto_state.
virtual void MenuState::on_exit(MenuContext *context)=0
Referenced by MenuContext::goto_state.
virtual void MenuState::update(MenuContext *context)=0
Referenced by MenuContext::update.