BatteryMonitorIP5306
const uint8_t BatteryMonitorIP5306::IP5306_I2C_ADDR
const uint8_t BatteryMonitorIP5306::IP5306_REG_SYS_0
const uint8_t BatteryMonitorIP5306::IP5306_REG_SYS_1
const uint8_t BatteryMonitorIP5306::IP5306_REG_SYS_2
const uint8_t BatteryMonitorIP5306::IP5306_REG_CHG_0
const uint8_t BatteryMonitorIP5306::IP5306_REG_CHG_1
const uint8_t BatteryMonitorIP5306::IP5306_REG_CHG_2
const uint8_t BatteryMonitorIP5306::IP5306_REG_CHG_3
const uint8_t BatteryMonitorIP5306::IP5306_REG_CHG_4
const uint8_t BatteryMonitorIP5306::IP5306_REG_READ_0
const uint8_t BatteryMonitorIP5306::IP5306_REG_READ_1
const uint8_t BatteryMonitorIP5306::IP5306_REG_READ_2
const uint8_t BatteryMonitorIP5306::IP5306_REG_READ_3
const uint8_t BatteryMonitorIP5306::IP5306_REG_READ_4
uint8_t BatteryMonitorIP5306::get_bits(uint8_t reg, uint8_t index, uint8_t bits)
void BatteryMonitorIP5306::set_bits(uint8_t reg, uint8_t index, uint8_t bits, uint8_t value)
int BatteryMonitorIP5306::get_reg(uint8_t reg)
int BatteryMonitorIP5306::set_reg(uint8_t reg, uint8_t value)
uint8_t BatteryMonitorIP5306::get_bits(uint8_t reg, uint8_t index, uint8_t bits)
void BatteryMonitorIP5306::set_bits(uint8_t reg, uint8_t index, uint8_t bits, uint8_t value)
int BatteryMonitorIP5306::get_reg(uint8_t reg)
int BatteryMonitorIP5306::set_reg(uint8_t reg, uint8_t value)
BatteryMonitorIP5306::BatteryMonitorIP5306()
void BatteryMonitorIP5306::print_stats()
References GetBatteryFull, GetLevelLeds, GetPowerSource, LEDS2PCT.
void BatteryMonitorIP5306::print_settings()
References GetBoostAfterVin, GetBoostEnabled, GetBoostOffClicks, GetBoostOutputEnabled, GetChargeCCLoop, GetChargeCutoffVoltage, GetChargerEnabled, GetChargeUnderVoltageLoop, GetChargingFullStopVoltage, GetEndChargeCurrentDetection, GetFlashlightClicks, GetKeyOffEnabled, GetLightLoadShutdownTime, GetLongPressTime, GetLowBatShutdownEnable, GetPowerOnLoadEnabled, GetShortPressBoostSwitchEnable, GetVinCurrent, GetVoltagePressure.
int8_t BatteryMonitorIP5306::get_level()
TodoIP5306 is replaced by AXP192 in the M5 Core2, this file serves no purpose.
uint8_t BatteryMonitorIP5306::GetKeyOffEnabled()
References IP5306_REG_SYS_0.
Referenced by print_settings.
void BatteryMonitorIP5306::SetKeyOffEnabled(uint8_t v)
References IP5306_REG_SYS_0.
uint8_t BatteryMonitorIP5306::GetBoostOutputEnabled()
References IP5306_REG_SYS_0.
Referenced by print_settings.
void BatteryMonitorIP5306::SetBoostOutputEnabled(uint8_t v)
References IP5306_REG_SYS_0.
uint8_t BatteryMonitorIP5306::GetPowerOnLoadEnabled()
References IP5306_REG_SYS_0.
Referenced by print_settings.
void BatteryMonitorIP5306::SetPowerOnLoadEnabled(uint8_t v)
References IP5306_REG_SYS_0.
uint8_t BatteryMonitorIP5306::GetChargerEnabled()
References IP5306_REG_SYS_0.
Referenced by print_settings.
void BatteryMonitorIP5306::SetChargerEnabled(uint8_t v)
References IP5306_REG_SYS_0.
uint8_t BatteryMonitorIP5306::GetBoostEnabled()
References IP5306_REG_SYS_0.
Referenced by print_settings.
void BatteryMonitorIP5306::SetBoostEnabled(uint8_t v)
References IP5306_REG_SYS_0.
uint8_t BatteryMonitorIP5306::GetLowBatShutdownEnable()
References IP5306_REG_SYS_1.
Referenced by print_settings.
void BatteryMonitorIP5306::SetLowBatShutdownEnable(uint8_t v)
References IP5306_REG_SYS_1.
uint8_t BatteryMonitorIP5306::GetBoostAfterVin()
References IP5306_REG_SYS_1.
Referenced by print_settings.
void BatteryMonitorIP5306::SetBoostAfterVin(uint8_t v)
References IP5306_REG_SYS_1.
uint8_t BatteryMonitorIP5306::GetShortPressBoostSwitchEnable()
References IP5306_REG_SYS_1.
Referenced by print_settings.
void BatteryMonitorIP5306::SetShortPressBoostSwitchEnable(uint8_t v)
References IP5306_REG_SYS_1.
uint8_t BatteryMonitorIP5306::GetFlashlightClicks()
References IP5306_REG_SYS_1.
Referenced by print_settings.
void BatteryMonitorIP5306::SetFlashlightClicks(uint8_t v)
References IP5306_REG_SYS_1.
uint8_t BatteryMonitorIP5306::GetBoostOffClicks()
References IP5306_REG_SYS_1.
Referenced by print_settings.
void BatteryMonitorIP5306::SetBoostOffClicks(uint8_t v)
References IP5306_REG_SYS_1.
uint8_t BatteryMonitorIP5306::GetLightLoadShutdownTime()
References IP5306_REG_SYS_2.
Referenced by print_settings.
void BatteryMonitorIP5306::SetLightLoadShutdownTime(uint8_t v)
References IP5306_REG_SYS_2.
uint8_t BatteryMonitorIP5306::GetLongPressTime()
References IP5306_REG_SYS_2.
Referenced by print_settings.
void BatteryMonitorIP5306::SetLongPressTime(uint8_t v)
References IP5306_REG_SYS_2.
uint8_t BatteryMonitorIP5306::GetChargingFullStopVoltage()
References IP5306_REG_CHG_0.
Referenced by print_settings.
void BatteryMonitorIP5306::SetChargingFullStopVoltage(uint8_t v)
References IP5306_REG_CHG_0.
uint8_t BatteryMonitorIP5306::GetChargeUnderVoltageLoop()
References IP5306_REG_CHG_1.
Referenced by print_settings.
void BatteryMonitorIP5306::SetChargeUnderVoltageLoop(uint8_t v)
References IP5306_REG_CHG_1.
uint8_t BatteryMonitorIP5306::GetEndChargeCurrentDetection()
References IP5306_REG_CHG_1.
Referenced by print_settings.
void BatteryMonitorIP5306::SetEndChargeCurrentDetection(uint8_t v)
References IP5306_REG_CHG_1.
uint8_t BatteryMonitorIP5306::GetVoltagePressure()
References IP5306_REG_CHG_2.
Referenced by print_settings.
void BatteryMonitorIP5306::SetVoltagePressure(uint8_t v)
References IP5306_REG_CHG_2.
uint8_t BatteryMonitorIP5306::GetChargeCutoffVoltage()
References IP5306_REG_CHG_2.
Referenced by print_settings.
void BatteryMonitorIP5306::SetChargeCutoffVoltage(uint8_t v)
References IP5306_REG_CHG_2.
uint8_t BatteryMonitorIP5306::GetChargeCCLoop()
References IP5306_REG_CHG_3.
Referenced by print_settings.
void BatteryMonitorIP5306::SetChargeCCLoop(uint8_t v)
References IP5306_REG_CHG_3.
uint8_t BatteryMonitorIP5306::GetVinCurrent()
References IP5306_REG_CHG_4.
Referenced by print_settings.
void BatteryMonitorIP5306::SetVinCurrent(uint8_t v)
References IP5306_REG_CHG_4.
uint8_t BatteryMonitorIP5306::GetShortPressDetected()
References IP5306_REG_READ_3.
void BatteryMonitorIP5306::ClearShortPressDetected()
References IP5306_REG_READ_3.
uint8_t BatteryMonitorIP5306::GetLongPressDetected()
References IP5306_REG_READ_3.
void BatteryMonitorIP5306::ClearLongPressDetected()
References IP5306_REG_READ_3.
uint8_t BatteryMonitorIP5306::GetDoubleClickDetected()
References IP5306_REG_READ_3.
void BatteryMonitorIP5306::ClearDoubleClickDetected()
References IP5306_REG_READ_3.
uint8_t BatteryMonitorIP5306::GetPowerSource()
References IP5306_REG_READ_0.
Referenced by print_stats.
uint8_t BatteryMonitorIP5306::GetBatteryFull()
References IP5306_REG_READ_1.
Referenced by print_stats.
uint8_t BatteryMonitorIP5306::GetOutputLoad()
References IP5306_REG_READ_2.
uint8_t BatteryMonitorIP5306::GetLevelLeds()
References IP5306_REG_READ_4.
Referenced by print_stats.
uint8_t BatteryMonitorIP5306::LEDS2PCT(uint8_t byte)
Referenced by print_stats.
BatteryMonitorIP5306::BatteryMonitorIP5306()
void BatteryMonitorIP5306::print_stats()
void BatteryMonitorIP5306::print_settings()
int8_t BatteryMonitorIP5306::get_level()
uint8_t BatteryMonitorIP5306::GetKeyOffEnabled()
References IP5306_REG_SYS_0.
void BatteryMonitorIP5306::SetKeyOffEnabled(uint8_t v)
References IP5306_REG_SYS_0.
uint8_t BatteryMonitorIP5306::GetBoostOutputEnabled()
References IP5306_REG_SYS_0.
void BatteryMonitorIP5306::SetBoostOutputEnabled(uint8_t v)
References IP5306_REG_SYS_0.
uint8_t BatteryMonitorIP5306::GetPowerOnLoadEnabled()
References IP5306_REG_SYS_0.
void BatteryMonitorIP5306::SetPowerOnLoadEnabled(uint8_t v)
References IP5306_REG_SYS_0.
uint8_t BatteryMonitorIP5306::GetChargerEnabled()
References IP5306_REG_SYS_0.
void BatteryMonitorIP5306::SetChargerEnabled(uint8_t v)
References IP5306_REG_SYS_0.
uint8_t BatteryMonitorIP5306::GetBoostEnabled()
References IP5306_REG_SYS_0.
void BatteryMonitorIP5306::SetBoostEnabled(uint8_t v)
References IP5306_REG_SYS_0.
uint8_t BatteryMonitorIP5306::GetLowBatShutdownEnable()
References IP5306_REG_SYS_1.
void BatteryMonitorIP5306::SetLowBatShutdownEnable(uint8_t v)
References IP5306_REG_SYS_1.
uint8_t BatteryMonitorIP5306::GetBoostAfterVin()
References IP5306_REG_SYS_1.
void BatteryMonitorIP5306::SetBoostAfterVin(uint8_t v)
References IP5306_REG_SYS_1.
uint8_t BatteryMonitorIP5306::GetShortPressBoostSwitchEnable()
References IP5306_REG_SYS_1.
void BatteryMonitorIP5306::SetShortPressBoostSwitchEnable(uint8_t v)
References IP5306_REG_SYS_1.
uint8_t BatteryMonitorIP5306::GetFlashlightClicks()
References IP5306_REG_SYS_1.
void BatteryMonitorIP5306::SetFlashlightClicks(uint8_t v)
References IP5306_REG_SYS_1.
uint8_t BatteryMonitorIP5306::GetBoostOffClicks()
References IP5306_REG_SYS_1.
void BatteryMonitorIP5306::SetBoostOffClicks(uint8_t v)
References IP5306_REG_SYS_1.
uint8_t BatteryMonitorIP5306::GetLightLoadShutdownTime()
References IP5306_REG_SYS_2.
void BatteryMonitorIP5306::SetLightLoadShutdownTime(uint8_t v)
References IP5306_REG_SYS_2.
uint8_t BatteryMonitorIP5306::GetLongPressTime()
References IP5306_REG_SYS_2.
void BatteryMonitorIP5306::SetLongPressTime(uint8_t v)
References IP5306_REG_SYS_2.
uint8_t BatteryMonitorIP5306::GetChargingFullStopVoltage()
References IP5306_REG_CHG_0.
void BatteryMonitorIP5306::SetChargingFullStopVoltage(uint8_t v)
References IP5306_REG_CHG_0.
uint8_t BatteryMonitorIP5306::GetChargeUnderVoltageLoop()
References IP5306_REG_CHG_1.
void BatteryMonitorIP5306::SetChargeUnderVoltageLoop(uint8_t v)
References IP5306_REG_CHG_1.
uint8_t BatteryMonitorIP5306::GetEndChargeCurrentDetection()
References IP5306_REG_CHG_1.
void BatteryMonitorIP5306::SetEndChargeCurrentDetection(uint8_t v)
References IP5306_REG_CHG_1.
uint8_t BatteryMonitorIP5306::GetVoltagePressure()
References IP5306_REG_CHG_2.
void BatteryMonitorIP5306::SetVoltagePressure(uint8_t v)
References IP5306_REG_CHG_2.
uint8_t BatteryMonitorIP5306::GetChargeCutoffVoltage()
References IP5306_REG_CHG_2.
void BatteryMonitorIP5306::SetChargeCutoffVoltage(uint8_t v)
References IP5306_REG_CHG_2.
uint8_t BatteryMonitorIP5306::GetChargeCCLoop()
References IP5306_REG_CHG_3.
void BatteryMonitorIP5306::SetChargeCCLoop(uint8_t v)
References IP5306_REG_CHG_3.
uint8_t BatteryMonitorIP5306::GetVinCurrent()
References IP5306_REG_CHG_4.
void BatteryMonitorIP5306::SetVinCurrent(uint8_t v)
References IP5306_REG_CHG_4.
uint8_t BatteryMonitorIP5306::GetShortPressDetected()
References IP5306_REG_READ_3.
void BatteryMonitorIP5306::ClearShortPressDetected()
References IP5306_REG_READ_3.
uint8_t BatteryMonitorIP5306::GetLongPressDetected()
References IP5306_REG_READ_3.
void BatteryMonitorIP5306::ClearLongPressDetected()
References IP5306_REG_READ_3.
uint8_t BatteryMonitorIP5306::GetDoubleClickDetected()
References IP5306_REG_READ_3.
void BatteryMonitorIP5306::ClearDoubleClickDetected()
References IP5306_REG_READ_3.
uint8_t BatteryMonitorIP5306::GetPowerSource()
References IP5306_REG_READ_0.
uint8_t BatteryMonitorIP5306::GetBatteryFull()
References IP5306_REG_READ_1.
uint8_t BatteryMonitorIP5306::GetOutputLoad()
References IP5306_REG_READ_2.
uint8_t BatteryMonitorIP5306::GetLevelLeds()
References IP5306_REG_READ_4.
uint8_t BatteryMonitorIP5306::LEDS2PCT(uint8_t byte)