ApiConnector
ApiHandlerStatus
HTTPClient ApiConnector::_http_client
LocalStorage& ApiConnector::_config
char ApiConnector::_payload[200][200]
uint32_t ApiConnector::_post_count
uint32_t ApiConnector::_last_post
ApiConnector::ApiConnector(LocalStorage &config)
virtual ApiConnector::~ApiConnector()=default
uint32_t ApiConnector::get_post_count() const
Referenced by FixedModeScreen::render.
bool ApiConnector::time_to_send(bool in_fixed_range, bool alert) const
Check if enough time has passed to send the latest reading to api in_fixed_range If within configured range, a different send frequency is used alert If alerted, a different send frequency is used true if time to send
References API_SEND_SECONDS_DELAY, API_SEND_SECONDS_DELAY_ALERT, API_SEND_SECONDS_DELAY_ROAMING, SEND_FREQUENCY.
Referenced by handle_produced_work.
bool ApiConnector::activate(bool retry) override
Initialize the connection initial set to false if its for reconnect / connect in error true if connection with the wifi was made
References clamp, WiFiWrapper::connect_wifi, LocalStorage::get_wifi_password, LocalStorage::get_wifi_ssid, RETRY_TIMEOUT, WiFiWrapper::wifi_connected, WiFiWrapper_i.
Referenced by handle_produced_work.
void ApiConnector::deactivate() override
Stop the connection
References clamp, WiFiWrapper::disconnect_wifi, WiFiWrapper_i.
int8_t ApiConnector::handle_produced_work(const worker_map_t &workers) override
References activate, clamp, e_api_reporter_error_not_connected, e_api_reporter_error_to_json, LocalStorage::get_alert_threshold, LocalStorage::get_fixed_device_id, k_worker_log_aggregator, log_aggregator, reading_to_json, time_to_send.
bool ApiConnector::reading_to_json(const DataLine &reading, char *out)
References clamp, LocalStorage::get_fixed_device_id, LocalStorage::get_fixed_latitude, LocalStorage::get_fixed_longitude.
Referenced by handle_produced_work.
int8_t ApiConnector::handle_async() override
References API_HOST, API_MEASUREMENTS_ENDPOINT, clamp, e_api_reporter_error_remote_not_available, e_api_reporter_error_server_rejected_post_400, e_api_reporter_error_server_rejected_post_401, e_api_reporter_error_server_rejected_post_403, e_api_reporter_error_server_rejected_post_5xx, e_api_reporter_send_success, LocalStorage::get_api_key, HEADER_API_CONTENT_TYPE, HEADER_API_USER_AGENT, WiFiWrapper::update_active, WiFiWrapper_i.