Setup
bool Setup::_ready
Preferences Setup::_prefs
ConfigData Setup::_config
DoseData Setup::_dose
WiFiParameters Setup::_wifiparams
Setup::Setup()
void Setup::initialize()
References SETUP_KEY_CONFIG, SETUP_KEY_DOSE, SETUP_NAMESPACE.
Referenced by Context::setup.
bool Setup::load_from_file(const char *setup_filename)
References ConfigData::alarm_level, clamp, ConfigData::country_code, ConfigData::cpm2bqm2_factor, ConfigData::cpm2ush_divider, ConfigData::device_id, LINE_PARSE_DELIM, LINE_PARSE_KEY, LINE_PARSE_VALUE, LINE_SKIP, LINE_START, ConfigData::mode, ConfigData::sensor_height, ConfigData::sensor_mode, ConfigData::sensor_shield, ConfigData::sensor_type, SETUP_DEFAULT_COUNTRY_CODE, SETUP_FILE_PARSE_BUFFER_SIZE, SETUP_KEY_CONFIG, SETUP_KEY_DOSE, SETUP_USERNAME_MAXLEN, ConfigData::timezone, ConfigData::type, ConfigData::user_name.
Referenced by Context::setup.
bool Setup::ready() const
const ConfigData & Setup::config() const
Referenced by Display::feed, StateWaitGPSTime::on_exit, StateLogging::process, Context::setup.
const DoseData & Setup::dose() const
const WiFiParameters & Setup::wifiparams() const
Setup::Setup()
void Setup::initialize()
bool Setup::load_from_file(const char *setup_filename)
bool Setup::ready() const
const ConfigData & Setup::config() const
const DoseData & Setup::dose() const