WiFiWrapper
char WiFiWrapper::_hostname[20][20]
uint32_t WiFiWrapper::_last_activity
WiFiWrapper::WiFiWrapper()
bool WiFiWrapper::connect_wifi(const char *ssid, const char *password=nullptr, bool first_time=false)
Connect to wifi endpoint ssid password true if connected
References clamp, update_active, wifi_connected.
Referenced by ApiConnector::activate, ConfigModeScreen::enter_screen.
void WiFiWrapper::disconnect_wifi()
disconnect from wifi endpoint
References clamp.
Referenced by ApiConnector::deactivate, ConfigModeScreen::leave_screen.
bool WiFiWrapper::wifi_connected()
check if wifi is connected
References clamp.
Referenced by ApiConnector::activate, connect_wifi, GFXScreen::handle_report, update_active.
uint8_t WiFiWrapper::status()
check if wifi is connected
References clamp.
Referenced by BaseScreen::get_error_message.
bool WiFiWrapper::start_ap_server(uint16_t device_id, const char *password)
Start access point server true if up
References ACCESS_POINT_IP, ACCESS_POINT_NMASK, ACCESS_POINT_SSID, clamp.
Referenced by ConfigModeScreen::enter_screen.
void WiFiWrapper::stop_ap_server()
Stop access point server
References ap_server_up, clamp.
Referenced by ConfigModeScreen::leave_screen.
bool WiFiWrapper::ap_server_up()
check if wifi is connected
References clamp.
Referenced by stop_ap_server.
void WiFiWrapper::set_hostname(const char *hostname, bool ap_mode)
Set wifi hostname
References clamp.
const char * WiFiWrapper::get_hostname() const
void WiFiWrapper::update_active()
References clamp, wifi_connected.
Referenced by connect_wifi, ApiConnector::handle_async.
bool WiFiWrapper::was_active()
References clamp.
Referenced by GFXScreen::handle_report.