TinyGPS
static const float TinyGPS::GPS_INVALID_F_ANGLE
Referenced by f_course, f_get_position.
static const float TinyGPS::GPS_INVALID_F_ALTITUDE
Referenced by f_altitude.
static const float TinyGPS::GPS_INVALID_F_SPEED
Referenced by f_speed_kmph, f_speed_knots, f_speed_mph, f_speed_mps.
unsigned long TinyGPS::_time
unsigned long TinyGPS::_new_time
unsigned long TinyGPS::_date
unsigned long TinyGPS::_new_date
long TinyGPS::_latitude
long TinyGPS::_new_latitude
long TinyGPS::_longitude
long TinyGPS::_new_longitude
long TinyGPS::_altitude
long TinyGPS::_new_altitude
unsigned long TinyGPS::_speed
unsigned long TinyGPS::_new_speed
unsigned long TinyGPS::_course
unsigned long TinyGPS::_new_course
unsigned long TinyGPS::_hdop
unsigned long TinyGPS::_new_hdop
unsigned short TinyGPS::_numsats
unsigned short TinyGPS::_new_numsats
unsigned long TinyGPS::_last_time_fix
unsigned long TinyGPS::_new_time_fix
unsigned long TinyGPS::_last_position_fix
unsigned long TinyGPS::_new_position_fix
uint8_t TinyGPS::_parity
bool TinyGPS::_is_checksum_term
char TinyGPS::_term[15]
uint8_t TinyGPS::_sentence_type
uint8_t TinyGPS::_term_number
uint8_t TinyGPS::_term_offset
bool TinyGPS::_gps_data_good
bool TinyGPS::_raw_enabled
unsigned long TinyGPS::_encoded_characters
unsigned short TinyGPS::_good_sentences
unsigned short TinyGPS::_failed_checksum
unsigned short TinyGPS::_passed_checksum
TinyGPS::TinyGPS(bool enable_raw=false)
References clamp.
bool TinyGPS::encode(char c)
References clamp.
Referenced by operator<<.
TinyGPS & TinyGPS::operator<<(char c)
References clamp, encode.
void TinyGPS::get_position(long *latitude, long *longitude, unsigned long *fix_age=0)
References clamp, GPS_INVALID_AGE, GPS_INVALID_FIX_TIME.
Referenced by f_get_position.
void TinyGPS::get_datetime(unsigned long *date, unsigned long *time, unsigned long *age=0)
References clamp, GPS_INVALID_AGE, GPS_INVALID_FIX_TIME.
Referenced by crack_datetime.
long TinyGPS::altitude()
unsigned long TinyGPS::course()
Referenced by cardinal.
unsigned long TinyGPS::speed()
unsigned short TinyGPS::satellites()
unsigned long TinyGPS::hdop()
bool TinyGPS::status()
void TinyGPS::f_get_position(float *latitude, float *longitude, unsigned long *fix_age=0)
References clamp, get_position, GPS_INVALID_ANGLE, GPS_INVALID_F_ANGLE.
void TinyGPS::crack_datetime(int *year, uint8_t *month, uint8_t *day, uint8_t *hour, uint8_t *minute, uint8_t *second, uint8_t *hundredths=0, unsigned long *fix_age=0)
References get_datetime.
float TinyGPS::f_altitude()
References GPS_INVALID_ALTITUDE, GPS_INVALID_F_ALTITUDE.
float TinyGPS::f_course()
References GPS_INVALID_ANGLE, GPS_INVALID_F_ANGLE.
float TinyGPS::f_speed_knots()
References GPS_INVALID_F_SPEED, GPS_INVALID_SPEED.
Referenced by f_speed_kmph, f_speed_mph, f_speed_mps.
float TinyGPS::f_speed_mph()
References _GPS_MPH_PER_KNOT, clamp, f_speed_knots, GPS_INVALID_F_SPEED.
float TinyGPS::f_speed_mps()
References _GPS_MPS_PER_KNOT, clamp, f_speed_knots, GPS_INVALID_F_SPEED.
float TinyGPS::f_speed_kmph()
References _GPS_KMPH_PER_KNOT, clamp, f_speed_knots, GPS_INVALID_F_SPEED.
void TinyGPS::stats(unsigned long *chars, unsigned short *good_sentences, unsigned short *failed_cs)
References clamp.
TinyGPS::TinyGPS(bool enable_raw=false)
bool TinyGPS::encode(char c)
TinyGPS & TinyGPS::operator<<(char c)
References clamp, encode.
void TinyGPS::get_position(long *latitude, long *longitude, unsigned long *fix_age=0)
void TinyGPS::get_datetime(unsigned long *date, unsigned long *time, unsigned long *age=0)
long TinyGPS::altitude()
unsigned long TinyGPS::course()
unsigned long TinyGPS::speed()
unsigned short TinyGPS::satellites()
unsigned long TinyGPS::hdop()
bool TinyGPS::status()
void TinyGPS::f_get_position(float *latitude, float *longitude, unsigned long *fix_age=0)
void TinyGPS::crack_datetime(int *year, uint8_t *month, uint8_t *day, uint8_t *hour, uint8_t *minute, uint8_t *second, uint8_t *hundredths=0, unsigned long *fix_age=0)
float TinyGPS::f_altitude()
float TinyGPS::f_course()
float TinyGPS::f_speed_knots()
float TinyGPS::f_speed_mph()
float TinyGPS::f_speed_mps()
float TinyGPS::f_speed_kmph()
void TinyGPS::stats(unsigned long *chars, unsigned short *good_sentences, unsigned short *failed_cs)
static int TinyGPS::library_version()
References _GPS_VERSION.
float TinyGPS::distance_between(float lat1, float long1, float lat2, float long2)
References clamp.
float TinyGPS::course_to(float lat1, float long1, float lat2, float long2)
References clamp, TWO_PI.
const char * TinyGPS::cardinal(float course)
References clamp, course.
static int TinyGPS::library_version()
References _GPS_VERSION.
static float TinyGPS::distance_between(float lat1, float long1, float lat2, float long2)
static float TinyGPS::course_to(float lat1, float long1, float lat2, float long2)
static const char * TinyGPS::cardinal(float course)
int TinyGPS::from_hex(char a)
unsigned long TinyGPS::parse_decimal()
unsigned long TinyGPS::parse_degrees()
unsigned long TinyGPS::parse_degrees_raw()
bool TinyGPS::term_complete()
bool TinyGPS::gpsisdigit(char c)
long TinyGPS::gpsatol(const char *str)
int TinyGPS::gpsstrcmp(const char *str1, const char *str2)
int TinyGPS::from_hex(char a)
unsigned long TinyGPS::parse_decimal()
unsigned long TinyGPS::parse_degrees()
unsigned long TinyGPS::parse_degrees_raw()
bool TinyGPS::term_complete()
bool TinyGPS::gpsisdigit(char c)
long TinyGPS::gpsatol(const char *str)
int TinyGPS::gpsstrcmp(const char *str1, const char *str2)