display.cpp
InitState mstate
Referenced by Display::update.
InactiveState inactivestate
Referenced by Display::update.
MenuContext mcontext
Referenced by Display::clear, Display::update.
void core2Brightness(uint8_t lvl, bool overdrive=false)
References clamp.
Referenced by Display::clear, Display::update.
void printFloat(float val, bool valid, int len, int prec)
References clamp.
Referenced by Display::draw_main, Display::draw_survey, loop.
void printFloatFont(float val, bool valid, int len, int prec, int y, int x, int font)
References clamp.
Referenced by Display::draw_main, Display::draw_survey, loop.
void printInt(unsigned long val, bool valid, int len)
References clamp.
Referenced by Display::draw_main, Display::draw_survey, loop, printDate.
void printIntFont(unsigned long val, bool valid, int len, int y, int x, int font)
References clamp.
Referenced by Display::draw_main, Display::draw_survey, loop.
void printDate(TinyGPSDate &d)
References clamp, printInt.
Referenced by Display::draw_main, Display::draw_survey, loop.
void printTime(TinyGPSTime &t)
References clamp.
Referenced by Display::draw_main, Display::draw_survey, loop.