display.hpp
constexpr uint8_t LEVEL_BRIGHT
Referenced by Display::clear, Display::update.
constexpr uint8_t LEVEL_DIMMED
Referenced by Display::update.
constexpr uint8_t LEVEL_BLANKED
Referenced by Display::update.
constexpr uint32_t DELAY_DIMMING_DEFAULT
constexpr uint32_t DELAY_BLANKING_DEFAULT
void printFloat(float val, bool valid, int len, int prec)
References clamp.
Referenced by loop.
void printFloatFont(float val, bool valid, int len, int prec, int y, int x, int font)
References clamp.
Referenced by loop.
void printInt(unsigned long val, bool valid, int len)
References clamp.
Referenced by loop.
void printIntFont(unsigned long val, bool valid, int len, int y, int x, int font)
References clamp.
Referenced by loop.
void printDate(TinyGPSDate &d)
References clamp, printInt.
Referenced by loop.
void printTime(TinyGPSTime &t)
References clamp.
Referenced by loop.