TinyGPSDecimal
TinyGPSPlus
bool TinyGPSDecimal::valid
bool TinyGPSDecimal::updated
uint32_t TinyGPSDecimal::lastCommitTime
int32_t TinyGPSDecimal::val
int32_t TinyGPSDecimal::newval
bool TinyGPSDecimal::isValid() const
Referenced by Display::draw_main, Display::draw_survey, loop.
bool TinyGPSDecimal::isUpdated() const
uint32_t TinyGPSDecimal::age() const
References clamp.
int32_t TinyGPSDecimal::value()
Referenced by TinyGPSCourse::deg, TinyGPSAltitude::feet, TinyGPSHDOP::hdop, TinyGPSAltitude::kilometers, TinyGPSSpeed::kmph, TinyGPSSpeed::knots, TinyGPSAltitude::meters, TinyGPSAltitude::miles, TinyGPSSpeed::mph, TinyGPSSpeed::mps.
TinyGPSDecimal::TinyGPSDecimal()
bool TinyGPSDecimal::isValid() const
bool TinyGPSDecimal::isUpdated() const
uint32_t TinyGPSDecimal::age() const
References clamp.
int32_t TinyGPSDecimal::value()
TinyGPSDecimal::TinyGPSDecimal()
void TinyGPSDecimal::commit()
void TinyGPSDecimal::set(const char *term)
void TinyGPSDecimal::commit()
void TinyGPSDecimal::set(const char *term)