TinyGPSLocation
TinyGPSPlus
bool TinyGPSLocation::valid
bool TinyGPSLocation::updated
RawDegrees TinyGPSLocation::rawLatData
RawDegrees TinyGPSLocation::rawLngData
RawDegrees TinyGPSLocation::rawNewLatData
RawDegrees TinyGPSLocation::rawNewLngData
char TinyGPSLocation::rawLatStrData[10]
char TinyGPSLocation::rawNewLatStrData[10]
char TinyGPSLocation::rawLngStrData[11]
char TinyGPSLocation::rawNewLngStrData[11]
uint32_t TinyGPSLocation::lastCommitTime
bool TinyGPSLocation::isValid() const
Referenced by Display::draw_main, Display::draw_survey, loop.
bool TinyGPSLocation::isUpdated() const
uint32_t TinyGPSLocation::age() const
References clamp.
const RawDegrees & TinyGPSLocation::rawLat()
const RawDegrees & TinyGPSLocation::rawLng()
const char * TinyGPSLocation::rawLatStr()
const char * TinyGPSLocation::rawLngStr()
double TinyGPSLocation::lat()
References RawDegrees::billionths, clamp, RawDegrees::deg, RawDegrees::negative.
Referenced by Display::draw_main, Display::draw_survey, loop.
double TinyGPSLocation::lng()
References RawDegrees::billionths, clamp, RawDegrees::deg, RawDegrees::negative.
Referenced by Display::draw_main, Display::draw_survey, loop.
TinyGPSLocation::TinyGPSLocation()
bool TinyGPSLocation::isValid() const
bool TinyGPSLocation::isUpdated() const
uint32_t TinyGPSLocation::age() const
References clamp.
const RawDegrees & TinyGPSLocation::rawLat()
const RawDegrees & TinyGPSLocation::rawLng()
const char * TinyGPSLocation::rawLatStr()
const char * TinyGPSLocation::rawLngStr()
double TinyGPSLocation::lat()
double TinyGPSLocation::lng()
TinyGPSLocation::TinyGPSLocation()
void TinyGPSLocation::commit()
void TinyGPSLocation::setLatitude(const char *term)
void TinyGPSLocation::setLongitude(const char *term)
void TinyGPSLocation::commit()
void TinyGPSLocation::setLatitude(const char *term)
void TinyGPSLocation::setLongitude(const char *term)