TinyGPSInteger
TinyGPSPlus
bool TinyGPSInteger::valid
bool TinyGPSInteger::updated
uint32_t TinyGPSInteger::lastCommitTime
uint32_t TinyGPSInteger::val
uint32_t TinyGPSInteger::newval
bool TinyGPSInteger::isValid() const
Referenced by Display::draw_main, Display::draw_survey, loop.
bool TinyGPSInteger::isUpdated() const
uint32_t TinyGPSInteger::age() const
References clamp.
uint32_t TinyGPSInteger::value()
Referenced by Display::draw_main, Display::draw_survey, loop.
TinyGPSInteger::TinyGPSInteger()
bool TinyGPSInteger::isValid() const
bool TinyGPSInteger::isUpdated() const
uint32_t TinyGPSInteger::age() const
References clamp.
uint32_t TinyGPSInteger::value()
TinyGPSInteger::TinyGPSInteger()
void TinyGPSInteger::commit()
void TinyGPSInteger::set(const char *term)
void TinyGPSInteger::commit()
void TinyGPSInteger::set(const char *term)