TinyGPSAltitude
double TinyGPSAltitude::meters()
References TinyGPSDecimal::value.
Referenced by Display::draw_main, Display::draw_survey, loop.
double TinyGPSAltitude::miles()
References _GPS_MILES_PER_METER, TinyGPSDecimal::value.
double TinyGPSAltitude::kilometers()
References _GPS_KM_PER_METER, TinyGPSDecimal::value.
double TinyGPSAltitude::feet()
References _GPS_FEET_PER_METER, TinyGPSDecimal::value.
double TinyGPSAltitude::meters()
References TinyGPSDecimal::value.
double TinyGPSAltitude::miles()
References _GPS_MILES_PER_METER, TinyGPSDecimal::value.
double TinyGPSAltitude::kilometers()
References _GPS_KM_PER_METER, TinyGPSDecimal::value.
double TinyGPSAltitude::feet()
References _GPS_FEET_PER_METER, TinyGPSDecimal::value.