TinyGPSDate
TinyGPSPlus
bool TinyGPSDate::valid
bool TinyGPSDate::updated
uint32_t TinyGPSDate::date
uint32_t TinyGPSDate::newDate
uint32_t TinyGPSDate::lastCommitTime
bool TinyGPSDate::isValid() const
bool TinyGPSDate::isUpdated() const
uint32_t TinyGPSDate::age() const
References clamp.
uint32_t TinyGPSDate::value()
uint16_t TinyGPSDate::year()
References year.
Referenced by StateWaitGPSTime::on_exit, StateLogging::process, year.
uint8_t TinyGPSDate::month()
Referenced by StateWaitGPSTime::on_exit, StateLogging::process.
uint8_t TinyGPSDate::day()
Referenced by StateWaitGPSTime::on_exit, StateLogging::process.
TinyGPSDate::TinyGPSDate()
bool TinyGPSDate::isValid() const
bool TinyGPSDate::isUpdated() const
uint32_t TinyGPSDate::age() const
References clamp.
uint32_t TinyGPSDate::value()
uint16_t TinyGPSDate::year()
uint8_t TinyGPSDate::month()
uint8_t TinyGPSDate::day()
TinyGPSDate::TinyGPSDate()
void TinyGPSDate::commit()
void TinyGPSDate::setDate(const char *term)
void TinyGPSDate::commit()
void TinyGPSDate::setDate(const char *term)