M48
; DRILL file {KiCad 7.99.0-unknown-07d7ccf46f~176~ubuntu22.04.1} date 2024-01-11T12:25:35+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-11T12:25:35+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.99.0-unknown-07d7ccf46f~176~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C5.000
%
G90
G05
T1
X11.174Y-6.014
X11.304Y-49.744
M30
