var dir_0d51b65a5d031670186c7df27b2c4d34 =
[
    [ "battery.cpp", "battery_8cpp.html", null ],
    [ "battery.hpp", "src_2battery_8hpp.html", "src_2battery_8hpp" ],
    [ "config.hpp", "src_2config_8hpp.html", "src_2config_8hpp" ],
    [ "configuration_server.cpp", "archive_2bgeigie__firmware__pio_2src_2configuration__server_8cpp.html", "archive_2bgeigie__firmware__pio_2src_2configuration__server_8cpp" ],
    [ "display.cpp", "display_8cpp.html", "display_8cpp" ],
    [ "display.hpp", "src_2display_8hpp.html", "src_2display_8hpp" ],
    [ "fsm_context.cpp", "fsm__context_8cpp.html", null ],
    [ "fsm_context.hpp", "src_2fsm__context_8hpp.html", "src_2fsm__context_8hpp" ],
    [ "fsm_state_base.hpp", "src_2fsm__state__base_8hpp.html", "src_2fsm__state__base_8hpp" ],
    [ "fsm_state_concrete.cpp", "fsm__state__concrete_8cpp.html", null ],
    [ "fsm_state_concrete.hpp", "src_2fsm__state__concrete_8hpp.html", "src_2fsm__state__concrete_8hpp" ],
    [ "geiger_counter.cpp", "geiger__counter_8cpp.html", null ],
    [ "geiger_counter.hpp", "src_2geiger__counter_8hpp.html", "src_2geiger__counter_8hpp" ],
    [ "gps.cpp", "gps_8cpp.html", null ],
    [ "gps.hpp", "src_2gps_8hpp.html", "src_2gps_8hpp" ],
    [ "hardwarecounter.cpp", "hardwarecounter_8cpp.html", "hardwarecounter_8cpp" ],
    [ "hardwarecounter.hpp", "src_2hardwarecounter_8hpp.html", "src_2hardwarecounter_8hpp" ],
    [ "logger.cpp", "logger_8cpp.html", "logger_8cpp" ],
    [ "logger.hpp", "src_2logger_8hpp.html", "src_2logger_8hpp" ],
    [ "main.cpp", "archive_2bgeigie__firmware__pio_2src_2main_8cpp.html", "archive_2bgeigie__firmware__pio_2src_2main_8cpp" ],
    [ "menu.cpp", "menu_8cpp.html", "menu_8cpp" ],
    [ "motion.cpp", "motion_8cpp.html", null ],
    [ "sd_wrapper.hpp", "src_2sd__wrapper_8hpp.html", "src_2sd__wrapper_8hpp" ],
    [ "setup.cpp", "setup_8cpp.html", "setup_8cpp" ],
    [ "setup.hpp", "src_2setup_8hpp.html", "src_2setup_8hpp" ],
    [ "TinyGPS++.cpp", "_tiny_g_p_s_09_09_8cpp.html", "_tiny_g_p_s_09_09_8cpp" ],
    [ "TinyGPS++.h", "src_2_tiny_g_p_s_09_09_8h.html", "src_2_tiny_g_p_s_09_09_8h" ],
    [ "wifi_connection.cpp", "archive_2bgeigie__firmware__pio_2src_2wifi__connection_8cpp.html", null ]
];