.TH "include/battery.hpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/battery.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <M5Stack\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBatteryMonitorIP5306\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
