.TH "Context" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Context
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fsm_context\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContext\fP ()"
.br
.ti -1c
.RI "void \fBbegin\fP ()"
.br
.ti -1c
.RI "void \fBloop\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.ti -1c
.RI "void \fBon_geiger_counter_available\fP ()"
.br
.ti -1c
.RI "void \fBon_gps_available\fP ()"
.br
.ti -1c
.RI "void \fBtransition_to\fP (\fBState\fP *next_state, \fBEvent\fP e)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSetup\fP \fBdevice_setup\fP"
.br
.ti -1c
.RI "\fBGeigerCounter\fP \fBgeiger_count\fP {\fBGEIGER_AVERAGING_PERIOD_S\fP, \fBGEIGER_PULSE_GPIO\fP}"
.br
.ti -1c
.RI "\fBGPSSensor\fP \fBgps\fP {\fBGPS_SERIAL_NUM\fP, \fBGPS_BAUD_RATE\fP}"
.br
.ti -1c
.RI "\fBBatteryMonitorIP5306\fP \fBbattery_monitor\fP"
.br
.ti -1c
.RI "\fBBGeigieLogFormatter\fP \fBbgeigie_formatter\fP"
.br
.ti -1c
.RI "\fBSDWrapper\fP \fBsd_wrapper\fP"
.br
.ti -1c
.RI "\fBSDLogger\fP \fBlogger\fP"
.br
.ti -1c
.RI "\fBDisplay\fP \fBdisplay\fP {\fBLCD_REFRESH_RATE\fP}"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBStateStartup\fP"
.br
.ti -1c
.RI "class \fBStateWaitGPSTime\fP"
.br
.ti -1c
.RI "class \fBStateLogging\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file fsm_context\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Context::Context ()\fC [inline]\fP"

.PP
Definition at line 47 of file fsm_context\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Context::begin ()"

.PP
Definition at line 6 of file fsm_context\&.cpp\&.
.SS "void Context::loop ()"

.PP
Definition at line 10 of file fsm_context\&.cpp\&.
.SS "void Context::on_geiger_counter_available ()\fC [protected]\fP"

.PP
Definition at line 69 of file fsm_context\&.cpp\&.
.SS "void Context::on_gps_available ()\fC [protected]\fP"

.PP
Definition at line 79 of file fsm_context\&.cpp\&.
.SS "void Context::setup ()\fC [protected]\fP"

.PP
Definition at line 19 of file fsm_context\&.cpp\&.
.SS "void Context::transition_to (\fBState\fP * next_state, \fBEvent\fP e)\fC [protected]\fP"

.PP
Definition at line 84 of file fsm_context\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBStateLogging\fP\fC [friend]\fP"

.PP
Definition at line 54 of file fsm_context\&.hpp\&.
.SS "friend class \fBStateStartup\fP\fC [friend]\fP"

.PP
Definition at line 52 of file fsm_context\&.hpp\&.
.SS "friend class \fBStateWaitGPSTime\fP\fC [friend]\fP"

.PP
Definition at line 53 of file fsm_context\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBatteryMonitorIP5306\fP Context::battery_monitor\fC [protected]\fP"

.PP
Definition at line 32 of file fsm_context\&.hpp\&.
.SS "\fBBGeigieLogFormatter\fP Context::bgeigie_formatter\fC [protected]\fP"

.PP
Definition at line 35 of file fsm_context\&.hpp\&.
.SS "\fBSetup\fP Context::device_setup\fC [protected]\fP"

.PP
Definition at line 29 of file fsm_context\&.hpp\&.
.SS "\fBDisplay\fP Context::display {\fBLCD_REFRESH_RATE\fP}\fC [protected]\fP"

.PP
Definition at line 38 of file fsm_context\&.hpp\&.
.SS "\fBGeigerCounter\fP Context::geiger_count {\fBGEIGER_AVERAGING_PERIOD_S\fP, \fBGEIGER_PULSE_GPIO\fP}\fC [protected]\fP"

.PP
Definition at line 30 of file fsm_context\&.hpp\&.
.SS "\fBGPSSensor\fP Context::gps {\fBGPS_SERIAL_NUM\fP, \fBGPS_BAUD_RATE\fP}\fC [protected]\fP"

.PP
Definition at line 31 of file fsm_context\&.hpp\&.
.SS "\fBSDLogger\fP Context::logger\fC [protected]\fP"

.PP
Definition at line 37 of file fsm_context\&.hpp\&.
.SS "\fBSDWrapper\fP Context::sd_wrapper\fC [protected]\fP"

.PP
Definition at line 36 of file fsm_context\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
