.TH "src/geiger_counter.cpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/geiger_counter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <geiger_counter\&.hpp>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
