.TH "include/geiger_counter.hpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/geiger_counter.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <array>\fP
.br
\fC#include <M5Stack\&.h>\fP
.br
\fC#include <config\&.hpp>\fP
.br
\fC#include <hardwarecounter\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGeigerCounter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
