.TH "include/gps.hpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/gps.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <M5Stack\&.h>\fP
.br
\fC#include <TinyGPS++\&.h>\fP
.br
\fC#include <config\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGPSSensor\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGPSState\fP { \fBGPS_Startup\fP, \fBGPS_Wait_GPGGA_Wait_GPRMC\fP, \fBGPS_Got_GPGGA_Wait_GPRMC\fP, \fBGPS_Got_GPRMC_Wait_GPGGA\fP, \fBGPS_Idle\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBGPSState\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIGPS_Startup \fP\fP
.TP
\fB\fIGPS_Wait_GPGGA_Wait_GPRMC \fP\fP
.TP
\fB\fIGPS_Got_GPGGA_Wait_GPRMC \fP\fP
.TP
\fB\fIGPS_Got_GPRMC_Wait_GPGGA \fP\fP
.TP
\fB\fIGPS_Idle \fP\fP
.PP
Definition at line 18 of file gps\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
