.TH "HardwareCounter" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HardwareCounter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hardwarecounter\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHardwareCounter\fP ()"
.br
.ti -1c
.RI "\fBHardwareCounter\fP (uint32_t delay_s, int gpio, pcnt_unit_t unit=PCNT_UNIT_0)"
.br
.ti -1c
.RI "uint32_t \fBget_last_count\fP ()"
.br
.ti -1c
.RI "void \fBbegin\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "bool \fBavailable\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "void \fBtimer_intr_handler\fP (void *arg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file hardwarecounter\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HardwareCounter::HardwareCounter ()\fC [inline]\fP"

.PP
Definition at line 38 of file hardwarecounter\&.hpp\&.
.SS "HardwareCounter::HardwareCounter (uint32_t delay_s, int gpio, pcnt_unit_t unit = \fCPCNT_UNIT_0\fP)\fC [inline]\fP"

.PP
Definition at line 39 of file hardwarecounter\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool HardwareCounter::available ()\fC [inline]\fP"

.PP
Definition at line 50 of file hardwarecounter\&.hpp\&.
.SS "void HardwareCounter::begin ()"

.PP
Definition at line 22 of file hardwarecounter\&.cpp\&.
.SS "uint32_t HardwareCounter::get_last_count ()\fC [inline]\fP"

.PP
Definition at line 42 of file hardwarecounter\&.hpp\&.
.SS "void HardwareCounter::reset ()"

.PP
Definition at line 70 of file hardwarecounter\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "void timer_intr_handler (void * arg)\fC [friend]\fP"

.PP
Definition at line 16 of file hardwarecounter\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
