.TH "src/hardwarecounter.cpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hardwarecounter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <hardwarecounter\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void IRAM_ATTR \fBpcnt_intr_handler\fP (void *arg)"
.br
.ti -1c
.RI "void IRAM_ATTR \fBtimer_intr_handler\fP (void *arg)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void IRAM_ATTR pcnt_intr_handler (void * arg)"

.PP
Definition at line 7 of file hardwarecounter\&.cpp\&.
.SS "void IRAM_ATTR timer_intr_handler (void * arg)"

.PP
Definition at line 16 of file hardwarecounter\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
