.TH "include/logger.hpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/logger.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <M5Stack\&.h>\fP
.br
\fC#include <config\&.hpp>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <gps\&.hpp>\fP
.br
\fC#include <geiger_counter\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBGeigieLogFormatter\fP"
.br
.ti -1c
.RI "class \fBSDLogger\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
