.TH "RawDegrees" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RawDegrees
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TinyGPS++\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRawDegrees\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBdeg\fP"
.br
.ti -1c
.RI "uint32_t \fBbillionths\fP"
.br
.ti -1c
.RI "bool \fBnegative\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file TinyGPS++\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RawDegrees::RawDegrees ()\fC [inline]\fP"

.PP
Definition at line 52 of file TinyGPS++\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t RawDegrees::billionths"

.PP
Definition at line 49 of file TinyGPS++\&.h\&.
.SS "uint16_t RawDegrees::deg"

.PP
Definition at line 48 of file TinyGPS++\&.h\&.
.SS "bool RawDegrees::negative"

.PP
Definition at line 50 of file TinyGPS++\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
