.TH "include/sd_wrapper.hpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/sd_wrapper.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <M5Stack\&.h>\fP
.br
\fC#include <config\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSDWrapper\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBsd_error_t\fP { \fBSD_ERR_NOT_READY\fP, \fBSD_ERR_FILE_OPEN_W_FAIL\fP, \fBSD_ERR_FILE_OPEN_R_FAIL\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBsd_error_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISD_ERR_NOT_READY \fP\fP
.TP
\fB\fISD_ERR_FILE_OPEN_W_FAIL \fP\fP
.TP
\fB\fISD_ERR_FILE_OPEN_R_FAIL \fP\fP
.PP
Definition at line 11 of file sd_wrapper\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
