.TH "SDLogger" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLogger
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logger\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSDLogger\fP ()"
.br
.ti -1c
.RI "bool \fBstart\fP (uint32_t device_id, uint16_t year, uint8_t month, uint8_t day)"
.br
.ti -1c
.RI "bool \fBready\fP () const"
.br
.ti -1c
.RI "bool \fBfolder_created\fP () const"
.br
.ti -1c
.RI "bool \fBlog\fP (const char *log_line) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file logger\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SDLogger::SDLogger ()\fC [inline]\fP"

.PP
Definition at line 52 of file logger\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SDLogger::folder_created () const\fC [inline]\fP"

.PP
Definition at line 56 of file logger\&.hpp\&.
.SS "bool SDLogger::log (const char * log_line) const"

.PP
Definition at line 120 of file logger\&.cpp\&.
.SS "bool SDLogger::ready () const\fC [inline]\fP"

.PP
Definition at line 55 of file logger\&.hpp\&.
.SS "bool SDLogger::start (uint32_t device_id, uint16_t year, uint8_t month, uint8_t day)"

.PP
Definition at line 77 of file logger\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
