.TH "src/setup.cpp" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/setup.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <config\&.hpp>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <setup\&.hpp>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLineParseState\fP { \fBLINE_START\fP, \fBLINE_PARSE_KEY\fP, \fBLINE_PARSE_DELIM\fP, \fBLINE_PARSE_VALUE\fP, \fBLINE_SKIP\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLineParseState\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILINE_START \fP\fP
.TP
\fB\fILINE_PARSE_KEY \fP\fP
.TP
\fB\fILINE_PARSE_DELIM \fP\fP
.TP
\fB\fILINE_PARSE_VALUE \fP\fP
.TP
\fB\fILINE_SKIP \fP\fP
.PP
Definition at line 33 of file setup\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
