.TH "StateWaitGPSTime" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StateWaitGPSTime
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fsm_state_concrete\&.hpp>\fP
.PP
Inherits \fBState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBon_enter\fP (\fBEvent\fP e)"
.br
.ti -1c
.RI "void \fBprocess\fP ()"
.br
.ti -1c
.RI "void \fBon_exit\fP (\fBEvent\fP e)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBStateWaitGPSTime\fP * \fBinstance\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBStateWaitGPSTime\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file fsm_state_concrete\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StateWaitGPSTime::StateWaitGPSTime ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 25 of file fsm_state_concrete\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBStateWaitGPSTime\fP * StateWaitGPSTime::instance ()\fC [static]\fP"

.PP
Definition at line 18 of file fsm_state_concrete\&.cpp\&.
.SS "void StateWaitGPSTime::on_enter (\fBEvent\fP e)\fC [virtual]\fP"

.PP
Implements \fBState\fP\&.
.PP
Definition at line 24 of file fsm_state_concrete\&.cpp\&.
.SS "void StateWaitGPSTime::on_exit (\fBEvent\fP e)\fC [virtual]\fP"

.PP
Implements \fBState\fP\&.
.PP
Definition at line 35 of file fsm_state_concrete\&.cpp\&.
.SS "void StateWaitGPSTime::process ()\fC [virtual]\fP"

.PP
Implements \fBState\fP\&.
.PP
Definition at line 25 of file fsm_state_concrete\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
