.TH "include/TinyGPS++.h" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/TinyGPS++.h
.SH SYNOPSIS
.br
.PP
\fC#include 'WProgram\&.h'\fP
.br
\fC#include <limits\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRawDegrees\fP"
.br
.ti -1c
.RI "struct \fBTinyGPSLocation\fP"
.br
.ti -1c
.RI "struct \fBTinyGPSDate\fP"
.br
.ti -1c
.RI "struct \fBTinyGPSTime\fP"
.br
.ti -1c
.RI "struct \fBTinyGPSDecimal\fP"
.br
.ti -1c
.RI "struct \fBTinyGPSInteger\fP"
.br
.ti -1c
.RI "struct \fBTinyGPSSpeed\fP"
.br
.ti -1c
.RI "struct \fBTinyGPSCourse\fP"
.br
.ti -1c
.RI "struct \fBTinyGPSAltitude\fP"
.br
.ti -1c
.RI "struct \fBTinyGPSHDOP\fP"
.br
.ti -1c
.RI "class \fBTinyGPSCustom\fP"
.br
.ti -1c
.RI "class \fBTinyGPSPlus\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_GPS_VERSION\fP   '1\&.0\&.2'"
.br
.ti -1c
.RI "#define \fB_GPS_MPH_PER_KNOT\fP   1\&.15077945"
.br
.ti -1c
.RI "#define \fB_GPS_MPS_PER_KNOT\fP   0\&.51444444"
.br
.ti -1c
.RI "#define \fB_GPS_KMPH_PER_KNOT\fP   1\&.852"
.br
.ti -1c
.RI "#define \fB_GPS_MILES_PER_METER\fP   0\&.00062137112"
.br
.ti -1c
.RI "#define \fB_GPS_KM_PER_METER\fP   0\&.001"
.br
.ti -1c
.RI "#define \fB_GPS_FEET_PER_METER\fP   3\&.2808399"
.br
.ti -1c
.RI "#define \fB_GPS_MAX_FIELD_SIZE\fP   15"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _GPS_FEET_PER_METER   3\&.2808399"

.PP
Definition at line 43 of file TinyGPS++\&.h\&.
.SS "#define _GPS_KM_PER_METER   0\&.001"

.PP
Definition at line 42 of file TinyGPS++\&.h\&.
.SS "#define _GPS_KMPH_PER_KNOT   1\&.852"

.PP
Definition at line 40 of file TinyGPS++\&.h\&.
.SS "#define _GPS_MAX_FIELD_SIZE   15"

.PP
Definition at line 44 of file TinyGPS++\&.h\&.
.SS "#define _GPS_MILES_PER_METER   0\&.00062137112"

.PP
Definition at line 41 of file TinyGPS++\&.h\&.
.SS "#define _GPS_MPH_PER_KNOT   1\&.15077945"

.PP
Definition at line 38 of file TinyGPS++\&.h\&.
.SS "#define _GPS_MPS_PER_KNOT   0\&.51444444"

.PP
Definition at line 39 of file TinyGPS++\&.h\&.
.SS "#define _GPS_VERSION   '1\&.0\&.2'"

.PP
Definition at line 37 of file TinyGPS++\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
