.TH "TinyGPSAltitude" 3 "Thu Mar 10 2022" "BGeigieZen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyGPSAltitude
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TinyGPS++\&.h>\fP
.PP
Inherits \fBTinyGPSDecimal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBmeters\fP ()"
.br
.ti -1c
.RI "double \fBmiles\fP ()"
.br
.ti -1c
.RI "double \fBkilometers\fP ()"
.br
.ti -1c
.RI "double \fBfeet\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 185 of file TinyGPS++\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double TinyGPSAltitude::feet ()\fC [inline]\fP"

.PP
Definition at line 190 of file TinyGPS++\&.h\&.
.SS "double TinyGPSAltitude::kilometers ()\fC [inline]\fP"

.PP
Definition at line 189 of file TinyGPS++\&.h\&.
.SS "double TinyGPSAltitude::meters ()\fC [inline]\fP"

.PP
Definition at line 187 of file TinyGPS++\&.h\&.
.SS "double TinyGPSAltitude::miles ()\fC [inline]\fP"

.PP
Definition at line 188 of file TinyGPS++\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BGeigieZen from the source code\&.
